export const coinsList = [
  { id: "01coin", symbol: "zoc", name: "01coin" },
  { id: "0chain", symbol: "zcn", name: "Zus" },
  { id: "0vix-protocol", symbol: "vix", name: "0VIX Protocol" },
  { id: "0x", symbol: "zrx", name: "0x Protocol" },
  { id: "0x0-ai-ai-smart-contract", symbol: "0x0", name: "0x0.ai: AI Smart Contract" },
  { id: "0xdao", symbol: "oxd", name: "0xDAO" },
  { id: "0xdao-v2", symbol: "oxd v2", name: "0xDAO V2" },
  { id: "0xmonero", symbol: "0xmr", name: "0xMonero" },
  { id: "0xtrade", symbol: "0xt", name: "0xTrade" },
  { id: "0xwallet-token", symbol: "0xw", name: "0xWallet Token" },
  {
    id: "12405-santa-rosa",
    symbol: "realt-s-12405-santa-rosa-dr-detroit-mi",
    name: "RealT - 12405 Santa Rosa Dr, Detroit, MI 48204",
  },
  { id: "12ships", symbol: "tshp", name: "12Ships" },
  { id: "1337", symbol: "1337", name: "Elite" },
  {
    id: "14066-santa-rosa",
    symbol: "realt-s-14066-santa-rosa-dr-detroit-mi",
    name: "RealT - 14066 Santa Rosa Dr, Detroit, MI 48238",
  },
  {
    id: "1617-s-avers",
    symbol: "realt-s-1617-s.avers-ave-chicago-il",
    name: "RealT - 1617 S Avers Ave, Chicago, IL 60623",
  },
  { id: "1art", symbol: "1art", name: "OneArt" },
  { id: "1bch", symbol: "1bch", name: "1BCH" },
  { id: "1box", symbol: "1box", name: "1BOX" },
  { id: "1doge", symbol: "1doge", name: "1Doge" },
  { id: "1eco", symbol: "1eco", name: "1eco" },
  { id: "1eth", symbol: "1eth", name: "1ETH" },
  { id: "1hive-water", symbol: "water", name: "1Hive Water" },
  { id: "1inch", symbol: "1inch", name: "1inch" },
  { id: "1inch-yvault", symbol: "yv1inch", name: "1INCH yVault" },
  { id: "1million-nfts", symbol: "1mil", name: "1MillionNFTs" },
  { id: "1minbet", symbol: "1mb", name: "1minBET" },
  { id: "1move token", symbol: "1mt", name: "1Move Token" },
  { id: "1peco", symbol: "1peco", name: "1peco" },
  { id: "1reward-token", symbol: "1rt", name: "1Reward Token" },
  { id: "1safu", symbol: "safu", name: "1SAFU" },
  { id: "1sol", symbol: "1sol", name: "1Sol" },
  { id: "1sol-io-wormhole", symbol: "1sol", name: "1sol.io (Wormhole)" },
  { id: "1world", symbol: "1wo", name: "1World" },
  { id: "2044-nuclear-apocalypse", symbol: "2044", name: "2044 Nuclear Apocalypse" },
  { id: "20weth-80bal", symbol: "20weth-80bal", name: "20WETH-80BAL" },
  { id: "28vck", symbol: "vck", name: "28VCK" },
  { id: "2acoin", symbol: "arms", name: "2ACoin" },
  { id: "2crazynft", symbol: "2crz", name: "2crazyNFT" },
  { id: "2g-carbon-coin", symbol: "2gcc", name: "2G Carbon Coin" },
  { id: "2local-2", symbol: "2lc", name: "2local" },
  { id: "2omb-finance", symbol: "2omb", name: "2omb" },
  { id: "2share", symbol: "2shares", name: "2SHARE" },
  { id: "300fit", symbol: "fit", name: "300FIT" },
  { id: "30mb-token", symbol: "3omb", name: "3OMB" },
  { id: "3air", symbol: "3air", name: "3air" },
  { id: "3-kingdoms-multiverse", symbol: "3km", name: "3 Kingdoms Multiverse" },
  { id: "3shares", symbol: "3share", name: "3Share" },
  { id: "3xcalibur", symbol: "xcal", name: "3xcalibur Ecosystem Token" },
  { id: "42-coin", symbol: "42", name: "42-coin" },
  {
    id: "4852-4854-w-cortez",
    symbol: "realt-s-4852-4854-w.cortez-st-chicago-il",
    name: "RealT - 4852-4854 W Cortez St, Chicago, IL 60651",
  },
  { id: "4artechnologies", symbol: "4art", name: "4ART Coin" },
  { id: "4d-twin-maps", symbol: "map", name: "4D Twin Maps" },
  { id: "4int", symbol: "4int", name: "4INT" },
  { id: "4jnet", symbol: "4jnet", name: "4JNET" },
  { id: "4mw", symbol: "4mw", name: "4 Meta World" },
  { id: "4play", symbol: "4play", name: "4PLAY" },
  { id: "50cent", symbol: "50c", name: "50Cent" },
  { id: "5g-cash", symbol: "vgc", name: "5G-CASH" },
  { id: "5km-run", symbol: "run", name: "5KM RUN" },
  { id: "7pixels", symbol: "7pxs", name: "7Pixels" },
  { id: "888tron", symbol: "888", name: "888tron" },
  { id: "88mph", symbol: "mph", name: "88mph" },
  { id: "8bitearn", symbol: "8bit", name: "8BITEARN" },
  { id: "8pay", symbol: "8pay", name: "8Pay" },
  { id: "8x8-protocol", symbol: "exe", name: "8X8 Protocol" },
  { id: "99defi", symbol: "99defi", name: "99Defi" },
  { id: "99starz", symbol: "stz", name: "99Starz" },
  { id: "9-lives-network", symbol: "ninefi", name: "9 Lives Network" },
  { id: "a4-finance", symbol: "a4", name: "A4 Finance" },
  { id: "aada-finance", symbol: "aada", name: "Aada Finance" },
  { id: "aag-ventures", symbol: "aag", name: "AAG" },
  { id: "aave", symbol: "aave", name: "Aave" },
  { id: "aave-aave", symbol: "aaave", name: "Aave AAVE" },
  { id: "aave-amm-bptbalweth", symbol: "aammbptbalweth", name: "Aave AMM BptBALWETH" },
  { id: "aave-amm-bptwbtcweth", symbol: "aammbptwbtcweth", name: "Aave AMM BptWBTCWETH" },
  { id: "aave-amm-dai", symbol: "aammdai", name: "Aave AMM DAI" },
  { id: "aave-amm-uniaaveweth", symbol: "aammuniaaveweth", name: "Aave AMM UniAAVEWETH" },
  { id: "aave-amm-unibatweth", symbol: "aammunibatweth", name: "Aave AMM UniBATWETH" },
  { id: "aave-amm-unicrvweth", symbol: "aammunicrvweth", name: "Aave AMM UniCRVWETH" },
  { id: "aave-amm-unidaiusdc", symbol: "aammunidaiusdc", name: "Aave AMM UniDAIUSDC" },
  { id: "aave-amm-unidaiweth", symbol: "aammunidaiweth", name: "Aave AMM UniDAIWETH" },
  { id: "aave-amm-unilinkweth", symbol: "aammunilinkweth", name: "Aave AMM UniLINKWETH" },
  { id: "aave-amm-unimkrweth", symbol: "aammunimkrweth", name: "Aave AMM UniMKRWETH" },
  { id: "aave-amm-unirenweth", symbol: "aammunirenweth", name: "Aave AMM UniRENWETH" },
  { id: "aave-amm-unisnxweth", symbol: "aammunisnxweth", name: "Aave AMM UniSNXWETH" },
  { id: "aave-amm-uniuniweth", symbol: "aammuniuniweth", name: "Aave AMM UniUNIWETH" },
  { id: "aave-amm-uniusdcweth", symbol: "aammuniusdcweth", name: "Aave AMM UniUSDCWETH" },
  { id: "aave-amm-uniwbtcusdc", symbol: "aammuniwbtcusdc", name: "Aave AMM UniWBTCUSDC" },
  { id: "aave-amm-uniwbtcweth", symbol: "aammuniwbtcweth", name: "Aave AMM UniWBTCWETH" },
  { id: "aave-amm-uniyfiweth", symbol: "aammuniyfiweth", name: "Aave AMM UniYFIWETH" },
  { id: "aave-amm-usdc", symbol: "aammusdc", name: "Aave AMM USDC" },
  { id: "aave-amm-usdt", symbol: "aammusdt", name: "Aave AMM USDT" },
  { id: "aave-amm-wbtc", symbol: "aammwbtc", name: "Aave AMM WBTC" },
  { id: "aave-amm-weth", symbol: "aammweth", name: "Aave AMM WETH" },
  { id: "aave-bal", symbol: "abal", name: "Aave BAL" },
  { id: "aave-balancer-pool-token", symbol: "abpt", name: "Aave Balancer Pool Token" },
  { id: "aave-bat", symbol: "abat", name: "Aave BAT" },
  { id: "aave-bat-v1", symbol: "abat", name: "Aave BAT v1" },
  { id: "aave-busd", symbol: "abusd", name: "Aave BUSD" },
  { id: "aave-busd-v1", symbol: "abusd", name: "Aave BUSD v1" },
  { id: "aave-crv", symbol: "acrv", name: "Aave CRV" },
  { id: "aave-dai", symbol: "adai", name: "Aave DAI" },
  { id: "aave-dai-v1", symbol: "adai", name: "Aave DAI v1" },
  { id: "aave-enj", symbol: "aenj", name: "Aave ENJ" },
  { id: "aave-enj-v1", symbol: "aenj", name: "Aave ENJ v1" },
  { id: "aave-eth-v1", symbol: "aeth", name: "Aave ETH v1" },
  { id: "aavegotchi", symbol: "ghst", name: "Aavegotchi" },
  { id: "aavegotchi-alpha", symbol: "alpha", name: "Aavegotchi ALPHA" },
  { id: "aavegotchi-fomo", symbol: "fomo", name: "Aavegotchi FOMO" },
  { id: "aavegotchi-fud", symbol: "fud", name: "Aavegotchi FUD" },
  { id: "aavegotchi-kek", symbol: "kek", name: "Aavegotchi KEK" },
  { id: "aave-gusd", symbol: "agusd", name: "Aave GUSD" },
  { id: "aave-interest-bearing-steth", symbol: "asteth", name: "Aave Interest Bearing STETH" },
  { id: "aave-knc", symbol: "aknc", name: "Aave KNC" },
  { id: "aave-knc-v1", symbol: "aknc", name: "Aave KNC v1" },
  { id: "aave-link", symbol: "alink", name: "Aave LINK" },
  { id: "aave-link-v1", symbol: "alink", name: "Aave LINK v1" },
  { id: "aave-mana", symbol: "amana", name: "Aave MANA" },
  { id: "aave-mana-v1", symbol: "amana", name: "Aave MANA v1" },
  { id: "aave-mkr", symbol: "amkr", name: "Aave MKR" },
  { id: "aave-mkr-v1", symbol: "amkr", name: "Aave MKR v1" },
  { id: "aave-polygon-aave", symbol: "amaave", name: "Aave Polygon AAVE" },
  { id: "aave-polygon-dai", symbol: "amdai", name: "Aave Polygon DAI" },
  { id: "aave-polygon-usdc", symbol: "amusdc", name: "Aave Polygon USDC" },
  { id: "aave-polygon-usdt", symbol: "amusdt", name: "Aave Polygon USDT" },
  { id: "aave-polygon-wbtc", symbol: "amwbtc", name: "Aave Polygon WBTC" },
  { id: "aave-polygon-weth", symbol: "amweth", name: "Aave Polygon WETH" },
  { id: "aave-polygon-wmatic", symbol: "amwmatic", name: "Aave Polygon WMATIC" },
  { id: "aave-rai", symbol: "arai", name: "Aave RAI" },
  { id: "aave-ren", symbol: "aren", name: "Aave REN" },
  { id: "aave-ren-v1", symbol: "aren", name: "Aave REN v1" },
  { id: "aave-snx", symbol: "asnx", name: "Aave SNX" },
  { id: "aave-snx-v1", symbol: "asnx", name: "Aave SNX v1" },
  { id: "aave-susd", symbol: "asusd", name: "Aave SUSD" },
  { id: "aave-susd-v1", symbol: "asusd", name: "Aave SUSD v1" },
  { id: "aave-tusd", symbol: "atusd", name: "Aave TUSD" },
  { id: "aave-tusd-v1", symbol: "atusd", name: "Aave TUSD v1" },
  { id: "aave-uni", symbol: "auni", name: "Aave UNI" },
  { id: "aave-usdc", symbol: "ausdc", name: "Aave USDC" },
  { id: "aave-usdc-v1", symbol: "ausdc", name: "Aave USDC v1" },
  { id: "aave-usdt", symbol: "ausdt", name: "Aave USDT" },
  { id: "aave-usdt-v1", symbol: "ausdt", name: "Aave USDT v1" },
  { id: "aave-wbtc", symbol: "awbtc", name: "Aave WBTC" },
  { id: "aave-wbtc-v1", symbol: "awbtc", name: "Aave WBTC v1" },
  { id: "aave-weth", symbol: "aweth", name: "Aave WETH" },
  { id: "aave-xsushi", symbol: "axsushi", name: "Aave XSUSHI" },
  { id: "aave-yfi", symbol: "ayfi", name: "Aave YFI" },
  { id: "aave-yvault", symbol: "yvaave", name: "Aave yVault" },
  { id: "aave-zrx", symbol: "azrx", name: "Aave ZRX" },
  { id: "aave-zrx-v1", symbol: "azrx", name: "Aave ZRX v1" },
  { id: "abachi", symbol: "abi", name: "Abachi" },
  { id: "abased", symbol: "$abased", name: "aBASED" },
  { id: "abcmeta", symbol: "meta", name: "ABCMETA" },
  { id: "abc-pos-pool", symbol: "abc", name: "ABC PoS Pool" },
  { id: "abel-finance", symbol: "abel", name: "ABEL Finance" },
  { id: "abell-coin", symbol: "abc", name: "Abell Coin" },
  { id: "abey", symbol: "abey", name: "Abey" },
  { id: "able-finance", symbol: "able", name: "Able Finance" },
  { id: "aboat-token", symbol: "aboat", name: "Aboat Token" },
  { id: "absolute-sync-token", symbol: "ast", name: "Absolute Sync" },
  { id: "acala", symbol: "aca", name: "Acala" },
  { id: "acala-dollar", symbol: "ausd", name: "Acala Dollar (Karura)" },
  { id: "acala-dollar-acala", symbol: "ausd", name: "Acala Dollar (Acala)" },
  { id: "aca-token", symbol: "aca", name: "ACA" },
  { id: "access-protocol", symbol: "acs", name: "Access Protocol" },
  { id: "acent", symbol: "ace", name: "Acent" },
  { id: "acestarter", symbol: "astar", name: "AceStarter" },
  { id: "acetoken", symbol: "ace", name: "ACEToken" },
  { id: "acet-token", symbol: "act", name: "Acet" },
  { id: "ac-exchange-token", symbol: "acxt", name: "ACDX Exchange" },
  { id: "achain", symbol: "act", name: "Achain" },
  { id: "acid", symbol: "acid", name: "Acid" },
  { id: "acknoledger", symbol: "ack", name: "AcknoLedger" },
  { id: "ac-milan-fan-token", symbol: "acm", name: "AC Milan Fan Token" },
  { id: "acoconut", symbol: "ac", name: "ACoconut" },
  { id: "acoin", symbol: "acoin", name: "Acoin" },
  { id: "acquire-fi", symbol: "acq", name: "Acquire.Fi" },
  { id: "acreage-coin", symbol: "acr", name: "Acreage Coin" },
  { id: "acria", symbol: "acria", name: "Acria.AI" },
  { id: "across-protocol", symbol: "acx", name: "Across Protocol" },
  { id: "acryptos", symbol: "acs", name: "ACryptoS" },
  { id: "acryptosi", symbol: "acsi", name: "ACryptoSI" },
  { id: "actinium", symbol: "acm", name: "Actinium" },
  { id: "action-coin", symbol: "actn", name: "Action Coin" },
  { id: "active-world-rewards-token", symbol: "awrt", name: "Active World Rewards" },
  { id: "acute-angle-cloud", symbol: "aac", name: "Double-A Chain" },
  { id: "acy-finance", symbol: "acy", name: "ACY Finance" },
  { id: "adacash", symbol: "adacash", name: "ADAcash" },
  { id: "adadao", symbol: "adao", name: "ADADao" },
  { id: "adamant", symbol: "addy", name: "Adamant" },
  { id: "adana-demirspor", symbol: "demir", name: "Adana Demirspor" },
  { id: "adanaspor-fan-token", symbol: "adana", name: "Adanaspor Fan Token" },
  { id: "adapad", symbol: "adapad", name: "ADAPad" },
  { id: "adappter-token", symbol: "adp", name: "Adappter" },
  { id: "adaswap", symbol: "asw", name: "AdaSwap" },
  { id: "adax", symbol: "adax", name: "ADAX" },
  { id: "adazoo", symbol: "zoo", name: "ADAZOO" },
  { id: "add-xyz-new", symbol: "add", name: "Add.xyz (NEW)" },
  { id: "adex", symbol: "adx", name: "Ambire AdEx" },
  { id: "ad-flex-token", symbol: "adf", name: "Ad Flex" },
  { id: "aditus", symbol: "adi", name: "Aditus" },
  { id: "ado-network", symbol: "ado", name: "ADO Protocol" },
  { id: "adonis-2", symbol: "adon", name: "Adonis" },
  { id: "adora-token", symbol: "ara", name: "Adora" },
  { id: "adreward", symbol: "ad", name: "ADreward" },
  { id: "adroverse", symbol: "adr", name: "Adroverse" },
  { id: "adshares", symbol: "ads", name: "Adshares" },
  { id: "adtoken", symbol: "adt", name: "adChain" },
  { id: "adv3nture-xyz-gemstone", symbol: "gem", name: "Adv3nture.xyz Gemstone" },
  { id: "adv3nture-xyz-gold", symbol: "gold", name: "Adv3nture.xyz Gold" },
  { id: "advanced-internet-block", symbol: "aib", name: "Advanced Integrated Blocks" },
  { id: "advanced-united-continent", symbol: "auc", name: "Advanced United Continent" },
  { id: "advantis", symbol: "advt", name: "Advantis" },
  { id: "adventure-gold", symbol: "agld", name: "Adventure Gold" },
  { id: "adventurer-gold", symbol: "gold", name: "Adventurer Gold" },
  { id: "advertise-coin", symbol: "adco", name: "Advertise Coin" },
  { id: "aeggs", symbol: "aeggs", name: "aEGGS" },
  { id: "aegis", symbol: "ags", name: "Aegis" },
  { id: "aegis-token-f7934368-2fb3-4091-9edc-39283e87f55d", symbol: "aeg", name: "Aegis Token" },
  { id: "aelf", symbol: "elf", name: "aelf" },
  { id: "aelin", symbol: "aelin", name: "Aelin" },
  { id: "aelysir", symbol: "ael", name: "Aelysir" },
  { id: "aen-smart-token", symbol: "aens", name: "AEN Smart" },
  { id: "aeon", symbol: "aeon", name: "Aeon" },
  { id: "aerarium-fi", symbol: "aera", name: "Aerarium Fi" },
  { id: "aerdrop", symbol: "aer", name: "Aerdrop" },
  { id: "aergo", symbol: "aergo", name: "Aergo" },
  { id: "aeron", symbol: "arnx", name: "Aeron" },
  { id: "aerovek-aviation", symbol: "aero", name: "Aerovek Aviation" },
  { id: "aeternity", symbol: "ae", name: "Aeternity" },
  { id: "aeur", symbol: "aeur", name: "AEUR" },
  { id: "aezora", symbol: "azr", name: "Azzure" },
  { id: "afen-blockchain", symbol: "afen", name: "AFEN Blockchain" },
  { id: "affinity", symbol: "afnty", name: "Affinity" },
  { id: "affyn", symbol: "fyn", name: "Affyn" },
  { id: "afin-coin", symbol: "afin", name: "Asian Fintech" },
  { id: "afkdao", symbol: "afk", name: "AFKDAO" },
  { id: "afrep", symbol: "afrep", name: "Afrep" },
  { id: "afreum", symbol: "afr", name: "Afreum" },
  { id: "afrix", symbol: "afx", name: "Afrix" },
  { id: "afrostar", symbol: "afro", name: "Afrostar" },
  { id: "afyonspor-fan-token", symbol: "afyon", name: "Afyonspor Fan Token" },
  { id: "aga-carbon-credit", symbol: "agac", name: "AGA Carbon Credit" },
  { id: "aga-carbon-rewards", symbol: "acar", name: "AGA Carbon Rewards" },
  { id: "agame", symbol: "ag", name: "AGAME" },
  { id: "aga-rewards", symbol: "edc", name: "Edcoin" },
  { id: "aga-token", symbol: "aga", name: "AGA" },
  { id: "agavecoin", symbol: "agvc", name: "AgaveCoin" },
  { id: "agave-token", symbol: "agve", name: "Agave" },
  { id: "agenor", symbol: "age", name: "Agenor" },
  { id: "ageofgods", symbol: "aog", name: "AgeOfGods" },
  { id: "age-of-tanks", symbol: "a.o.t", name: "Age Of Tanks" },
  { id: "age-of-zalmoxis-koson", symbol: "koson", name: "Age of Zalmoxis KOSON" },
  { id: "ageur", symbol: "ageur", name: "agEUR" },
  { id: "ageur-plenty-bridge", symbol: "egeur.e", name: "agEUR (Plenty Bridge)" },
  { id: "aggle-io", symbol: "aggl", name: "aggle.io" },
  { id: "aggregated-finance", symbol: "agfi", name: "Aggregated Finance" },
  { id: "agile", symbol: "agl", name: "Agile" },
  { id: "agility", symbol: "agi", name: "Agility" },
  { id: "agora-defi", symbol: "agora", name: "Agora Defi" },
  { id: "agoras-currency-of-tau", symbol: "agrs", name: "Agoras: Currency of Tau" },
  { id: "agoric", symbol: "bld", name: "Agoric" },
  { id: "agrello", symbol: "dlt", name: "Agrello" },
  { id: "agricoin", symbol: "agn", name: "Agricoin" },
  { id: "agrinode", symbol: "agn", name: "AgriNode" },
  { id: "agro-global", symbol: "agro", name: "Agro Global" },
  { id: "agronomist", symbol: "agte", name: "Agronomist" },
  { id: "agx-coin", symbol: "agx", name: "AGX Coin" },
  { id: "ahatoken", symbol: "aht", name: "AhaToken" },
  { id: "a-hunters-dream", symbol: "caw", name: "A Hunters Dream" },
  { id: "aibra", symbol: "abr", name: "AIBRA" },
  { id: "ai-card-render", symbol: "acr", name: "AI Card Render" },
  { id: "aichain", symbol: "ait", name: "AICHAIN" },
  { id: "aicon", symbol: "aico", name: "Aicon" },
  { id: "aidcoin", symbol: "aid", name: "AidCoin" },
  { id: "aidi-finance-2", symbol: "aidi", name: "Aidi Finance" },
  { id: "ai-dogemini", symbol: "aidogemini", name: "AI DogeMini" },
  { id: "aidos-kuneen", symbol: "adk", name: "Aidos Kuneen" },
  { id: "ai-floki", symbol: "aifloki", name: "AI Floki" },
  { id: "aimedis-new", symbol: "aimx", name: "Aimedis (NEW)" },
  { id: "ai-network", symbol: "ain", name: "AI Network" },
  { id: "ainu-token", symbol: "ainu", name: "Ainu" },
  { id: "aion", symbol: "aion", name: "Aion" },
  { id: "aioz-network", symbol: "aioz", name: "AIOZ Network" },
  { id: "aipad", symbol: "aipad", name: "AIPad" },
  { id: "aipro", symbol: "aipro", name: "AIPRO" },
  { id: "airbloc-protocol", symbol: "abl", name: "Airbloc" },
  { id: "aircoin-2", symbol: "air", name: "AirCoin" },
  { id: "aircoins", symbol: "airx", name: "Aircoins" },
  { id: "airight", symbol: "airi", name: "aiRight" },
  { id: "airnft-token", symbol: "airt", name: "AirNFT" },
  { id: "airswap", symbol: "ast", name: "AirSwap" },
  { id: "airtnt", symbol: "airtnt", name: "AirTnT" },
  { id: "airtor-protocol", symbol: "ator", name: "AirTor Protocol" },
  { id: "aishiba", symbol: "shibai", name: "AiShiba" },
  { id: "ai-smart-chain", symbol: "aisc", name: "Ai Smart Chain" },
  { id: "ai-trader", symbol: "ait", name: "AI Trader" },
  { id: "aitravis", symbol: "tai", name: "AITravis" },
  { id: "aiwallet", symbol: "aiwallet", name: "AiWallet" },
  { id: "aiwork", symbol: "awo", name: "AiWork" },
  { id: "ajuna-network", symbol: "baju", name: "Ajuna Network" },
  { id: "akash-network", symbol: "akt", name: "Akash Network" },
  { id: "aki-protocol", symbol: "aki", name: "Aki Protocol" },
  { id: "akita-dao", symbol: "hachi", name: "Akita DAO" },
  { id: "akita-inu", symbol: "akita", name: "Akita Inu" },
  { id: "akita-inu-asa", symbol: "akta", name: "Akita Inu ASA" },
  { id: "akitavax", symbol: "akitax", name: "Akitavax" },
  { id: "akitsuki", symbol: "aki", name: "Akitsuki" },
  { id: "akoin", symbol: "akn", name: "Akoin" },
  { id: "akroma", symbol: "aka", name: "Akroma" },
  { id: "akropolis", symbol: "akro", name: "Akropolis" },
  { id: "akropolis-delphi", symbol: "adel", name: "Delphi" },
  { id: "aktio", symbol: "aktio", name: "Aktio" },
  { id: "aladdin-cvxcrv", symbol: "acrv", name: "Aladdin cvxCRV" },
  { id: "aladdin-dao", symbol: "ald", name: "Aladdin DAO" },
  { id: "alanyaspor-fan-token", symbol: "ala", name: "Alanyaspor Fan Token" },
  { id: "alaska-gold-rush", symbol: "carat", name: "Alaska Gold Rush" },
  { id: "alaya", symbol: "atp", name: "Alaya" },
  { id: "albedo", symbol: "albedo", name: "ALBEDO" },
  { id: "alcazar", symbol: "alcazar", name: "Alcazar" },
  { id: "alchemist", symbol: "mist", name: "Alchemist" },
  { id: "alchemix", symbol: "alcx", name: "Alchemix" },
  { id: "alchemix-eth", symbol: "aleth", name: "Alchemix ETH" },
  { id: "alchemix-usd", symbol: "alusd", name: "Alchemix USD" },
  { id: "alchemy-pay", symbol: "ach", name: "Alchemy Pay" },
  { id: "aldrin", symbol: "rin", name: "Aldrin" },
  { id: "aleph", symbol: "aleph", name: "Aleph.im" },
  { id: "alephium", symbol: "alph", name: "Alephium" },
  { id: "aleph-zero", symbol: "azero", name: "Aleph Zero" },
  { id: "alert", symbol: "alert", name: "ALERT" },
  { id: "alethea-artificial-liquid-intelligence-token", symbol: "ali", name: "Artificial Liquid Intelligence" },
  { id: "alexgo", symbol: "alex", name: "ALEX Lab" },
  { id: "alfa-romeo-racing-orlen-fan-token", symbol: "sauber", name: "Alfa Romeo Racing ORLEN Fan Token" },
  { id: "alfprotocol", symbol: "alf", name: "AlfProtocol" },
  { id: "algebra", symbol: "algb", name: "Algebra" },
  { id: "algoblocks", symbol: "algoblk", name: "AlgoBlocks" },
  { id: "algodao", symbol: "adao", name: "AlgoDAO" },
  { id: "algofund", symbol: "algf", name: "AlgoFund" },
  { id: "algomint", symbol: "gomint", name: "Algomint" },
  { id: "algorand", symbol: "algo", name: "Algorand" },
  { id: "algory", symbol: "alg", name: "Algory" },
  { id: "algostable", symbol: "stbl", name: "AlgoStable" },
  { id: "algostake", symbol: "stke", name: "AlgoStake" },
  { id: "alibabacoin", symbol: "abbc", name: "ABBC" },
  { id: "alibaba-tokenized-stock-defichain", symbol: "dbaba", name: "Alibaba Tokenized Stock Defichain" },
  { id: "alicenet", symbol: "alca", name: "AliceNet" },
  { id: "alien-chicken-farm", symbol: "acf", name: "Alien Chicken Farm" },
  { id: "alienfi", symbol: "alien", name: "AlienFi" },
  { id: "alien-inu", symbol: "alien", name: "Alien Inu" },
  { id: "alienswap", symbol: "alien", name: "AlienSwap" },
  { id: "alien-worlds", symbol: "tlm", name: "Alien Worlds" },
  { id: "alif-coin", symbol: "alif", name: "AliF Coin" },
  { id: "alink-ai", symbol: "alink", name: "ALINK AI" },
  { id: "alita", symbol: "ali", name: "Alita" },
  { id: "alitas", symbol: "alt", name: "Alitas" },
  { id: "alium-finance", symbol: "alm", name: "Alium Finance" },
  { id: "alkimi", symbol: "$ads", name: "Alkimi" },
  { id: "all-art", symbol: "aart", name: "ALL.ART" },
  { id: "allbridge", symbol: "abr", name: "Allbridge" },
  { id: "all-coins-yield-capital", symbol: "acyc", name: "All Coins Yield Capital" },
  { id: "allianceblock", symbol: "albt", name: "AllianceBlock" },
  { id: "allianceblock-nexera", symbol: "nxra", name: "AllianceBlock Nexera" },
  { id: "alliance-fan-token", symbol: "all", name: "Alliance Fan Token" },
  { id: "alliance-x-trading", symbol: "axt", name: "Alliance X Trading" },
  { id: "all-in", symbol: "allin", name: "All In" },
  { id: "all-in-ai", symbol: "aiai", name: "ALLINAI" },
  { id: "all-in-gpt", symbol: "aigpt", name: "All In GPT" },
  { id: "allium-finance", symbol: "alm", name: "Allium Finance" },
  { id: "all-me", symbol: "me", name: "All.me" },
  { id: "allpaycoin", symbol: "apcg", name: "ALLPAYCOIN" },
  { id: "allsafe", symbol: "asafe", name: "AllSafe" },
  { id: "all-sports-2", symbol: "soc", name: "All Sports" },
  { id: "allstars", symbol: "asx", name: "AllStars" },
  { id: "all-time-high", symbol: "ath", name: "All Time High" },
  { id: "alluo", symbol: "alluo", name: "Alluo" },
  { id: "ally", symbol: "aly", name: "Ally" },
  { id: "ally-direct", symbol: "drct", name: "Ally Direct" },
  { id: "almira-wallet", symbol: "almr", name: "Almira Wallet" },
  { id: "almond", symbol: "alm", name: "Almond" },
  { id: "alnair-finance-nika", symbol: "nika", name: "Alnair Finance NIKA" },
  { id: "alnassr-fc-fan-token", symbol: "nassr", name: "Alnassr FC Fan Token" },
  { id: "aloha", symbol: "aloha", name: "Aloha" },
  { id: "alongside-crypto-market-index", symbol: "amkt", name: "Alongside Crypto Market Index" },
  { id: "alon-mars", symbol: "alonmars", name: "Alon Mars" },
  { id: "alpaca", symbol: "alpa", name: "Alpaca City" },
  { id: "alpaca-finance", symbol: "alpaca", name: "Alpaca Finance" },
  { id: "alpha5", symbol: "a5t", name: "Alpha5" },
  { id: "alphabet", symbol: "alt", name: "Alphabet" },
  { id: "alpha-brain-capital-2", symbol: "acap", name: "Alpha Capital" },
  { id: "alphacoin", symbol: "alpha", name: "Alpha Coin" },
  { id: "alpha-dex", symbol: "roar", name: "Alpha DEX" },
  { id: "alpha-finance", symbol: "alpha", name: "Alpha Venture DAO" },
  { id: "alpha-intelligence", symbol: "$ai", name: "Alpha Intelligence" },
  { id: "alpha-quark-token", symbol: "aqt", name: "Alpha Quark" },
  { id: "alpharushai", symbol: "rushai", name: "AlphaRushAI" },
  { id: "alpha-shares-v2", symbol: "$alpha", name: "Alpha Shares V2" },
  { id: "alphatoken", symbol: ".alpha", name: ".Alpha" },
  { id: "alphr", symbol: "alphr", name: "Alphr" },
  { id: "alpine-f1-team-fan-token", symbol: "alpine", name: "Alpine F1 Team Fan Token" },
  { id: "altair", symbol: "air", name: "Altair" },
  { id: "altava", symbol: "tava", name: "ALTAVA" },
  { id: "altbase", symbol: "altb", name: "Altbase" },
  { id: "altcommunity-coin", symbol: "altom", name: "ALTOM" },
  { id: "alter", symbol: "alter", name: "Alter" },
  { id: "altered-state-token", symbol: "asto", name: "Altered State Machine" },
  { id: "altfins", symbol: "afins", name: "altFINS" },
  { id: "altfolio", symbol: "alt", name: "altfolio" },
  { id: "alt-markets", symbol: "amx", name: "Alt Markets" },
  { id: "altrucoin-2", symbol: "altrucoin", name: "Altrucoin" },
  { id: "altswitch", symbol: "alts", name: "AltSwitch" },
  { id: "altura", symbol: "alu", name: "Altura" },
  { id: "aluna", symbol: "aln", name: "Aluna" },
  { id: "alvey-chain", symbol: "walv", name: "Alvey Chain" },
  { id: "alyattes", symbol: "alya", name: "Alyattes" },
  { id: "amasa", symbol: "amas", name: "Amasa" },
  { id: "amateras", symbol: "amt", name: "Amateras" },
  { id: "amaterasufi-izanagi", symbol: "iza", name: "AmaterasuFi Izanagi" },
  { id: "amaurot", symbol: "ama", name: "AMAUROT" },
  { id: "amax-network", symbol: "amax", name: "AMAX Network" },
  { id: "amazewallet", symbol: "amt", name: "AmazeToken" },
  { id: "amazingdoge", symbol: "adoge", name: "AmazingDoge" },
  { id: "amazingteamdao", symbol: "amazingteam", name: "AmazingTeamDAO" },
  { id: "amazon-tokenized-stock-defichain", symbol: "damzn", name: "Amazon Tokenized Stock Defichain" },
  { id: "amazy", symbol: "azy", name: "Amazy" },
  { id: "amazy-move-token", symbol: "amt", name: "Amazy Move Token" },
  { id: "amber", symbol: "amb", name: "AirDAO" },
  { id: "ambire-wallet", symbol: "wallet", name: "Ambire Wallet" },
  { id: "amdg-token", symbol: "amdg", name: "AMDG" },
  { id: "amepay", symbol: "ame", name: "AME Chain" },
  { id: "american-shiba", symbol: "ushiba", name: "American Shiba" },
  { id: "amgen", symbol: "amg", name: "Amgen" },
  { id: "amlp", symbol: "amlp", name: "aMLP" },
  { id: "ammf", symbol: "ammf", name: "aMMF" },
  { id: "ammyi-coin", symbol: "ami", name: "AMMYI Coin" },
  { id: "amo", symbol: "amo", name: "AMO Coin" },
  { id: "amond", symbol: "amon", name: "AmonD" },
  { id: "ampleforth", symbol: "ampl", name: "Ampleforth" },
  { id: "ampleforth-governance-token", symbol: "forth", name: "Ampleforth Governance" },
  { id: "ampleswap", symbol: "ample", name: "AmpleSwap" },
  { id: "amplifi-dao", symbol: "agg", name: "AmpliFi DAO" },
  { id: "ampnet", symbol: "aapx", name: "AMPnet" },
  { id: "amp-token", symbol: "amp", name: "Amp" },
  { id: "amulet-staked-sol", symbol: "amtsol", name: "Amulet Staked SOL" },
  { id: "amz-coin", symbol: "amz", name: "AMZ Coin" },
  { id: "anarchy", symbol: "anarchy", name: "Anarchy" },
  { id: "a-nation", symbol: "anation", name: "A-Nation" },
  { id: "anchor-protocol", symbol: "anc", name: "Anchor Protocol" },
  { id: "anchorswap", symbol: "anchor", name: "AnchorSwap" },
  { id: "ancient-kingdom", symbol: "dom", name: "Ancient Kingdom" },
  { id: "ancient-raid", symbol: "raid", name: "Ancient Raid" },
  { id: "andronodes", symbol: "andro", name: "AndroNodes" },
  { id: "anduschain", symbol: "deb", name: "Anduschain" },
  { id: "angel-dust", symbol: "ad", name: "Angel Dust" },
  { id: "angelscreed", symbol: "angel", name: "AngelsCreed" },
  { id: "angle-protocol", symbol: "angle", name: "ANGLE" },
  { id: "angola", symbol: "agla", name: "Angola" },
  { id: "angryb", symbol: "anb", name: "Angryb" },
  { id: "angry-bulls-club", symbol: "abc", name: "Angry Bulls Club" },
  { id: "anifi-world", symbol: "anifi", name: "AniFi World" },
  { id: "animal-concerts-token", symbol: "anml", name: "Animal Concerts" },
  { id: "animal-farm", symbol: "afd", name: "Animal Farm Dogs" },
  { id: "animeswap", symbol: "ani", name: "AnimeSwap" },
  { id: "anime-token", symbol: "ani", name: "Anime" },
  { id: "animverse", symbol: "anm", name: "Animverse" },
  { id: "aniverse", symbol: "anv", name: "Aniverse" },
  { id: "aniverse-metaverse", symbol: "aniv", name: "Aniverse Metaverse" },
  { id: "anji", symbol: "anji", name: "Anji" },
  { id: "ankaragucu-fan-token", symbol: "anka", name: "Ankaragücü Fan Token" },
  { id: "ankr", symbol: "ankr", name: "Ankr Network" },
  { id: "ankreth", symbol: "ankreth", name: "Ankr Staked ETH" },
  { id: "ankr-reward-bearing-ftm", symbol: "ankrftm", name: "Ankr Staked FTM" },
  { id: "ankr-reward-earning-matic", symbol: "ankrmatic", name: "Ankr Staked MATIC" },
  { id: "ankr-staked-avax", symbol: "ankravax", name: "Ankr Staked AVAX" },
  { id: "ankr-staked-bnb", symbol: "ankrbnb", name: "Ankr Staked BNB" },
  { id: "anomus-coin", symbol: "anom", name: "Anomus Coin" },
  { id: "anon", symbol: "anon", name: "ANON" },
  { id: "anon-inu", symbol: "ainu", name: "Anon Inu" },
  { id: "anonydoxx", symbol: "adxx", name: "AnonyDoxx" },
  { id: "anonymous-bsc", symbol: "anon", name: "Anonymous BSC" },
  { id: "anonzk", symbol: "azk", name: "AnonZK" },
  { id: "another-world", symbol: "awm", name: "Another World" },
  { id: "anrkey-x", symbol: "$anrx", name: "AnRKey X" },
  { id: "answer-governance", symbol: "agov", name: "Answer Governance" },
  { id: "answerly", symbol: "ansr", name: "Answerly" },
  { id: "antalyaspor", symbol: "akrep", name: "Antalyaspor" },
  { id: "antedao", symbol: "ante", name: "AnteDAO" },
  { id: "antfarm-governance-token", symbol: "agt", name: "Antfarm Governance Token" },
  { id: "antfarm-token", symbol: "atf", name: "Antfarm Token" },
  { id: "antgold", symbol: "antg", name: "AntGold" },
  { id: "antiample", symbol: "xamp", name: "Antiample" },
  { id: "antimatter", symbol: "matter", name: "AntiMatter" },
  { id: "antnetworx", symbol: "antx", name: "AntNetworX" },
  { id: "anubit", symbol: "anb", name: "Anubit" },
  { id: "any-blocknet", symbol: "ablock", name: "ANY Blocknet" },
  { id: "anypad", symbol: "apad", name: "Anypad" },
  { id: "anyswap", symbol: "any", name: "Anyswap" },
  { id: "aok", symbol: "aok", name: "AOK" },
  { id: "aonea-coin", symbol: "a1a", name: "Aonea Coin" },
  { id: "apass-coin", symbol: "apc", name: "APass Coin" },
  { id: "apch", symbol: "apch", name: "APCH" },
  { id: "apecoin", symbol: "ape", name: "ApeCoin" },
  { id: "aped", symbol: "aped", name: "Aped" },
  { id: "apedoge", symbol: "aped", name: "Apedoge" },
  { id: "ape-finance", symbol: "apefi", name: "Ape Finance" },
  { id: "ape-fun-token", symbol: "aft", name: "Ape Fun" },
  { id: "ape-in", symbol: "apein", name: "Ape In" },
  { id: "ape_in_records", symbol: "air", name: "Ape In Records" },
  { id: "apejet", symbol: "jet", name: "ApeJet" },
  { id: "apemove", symbol: "ape", name: "APEmove" },
  { id: "apenft", symbol: "nft", name: "APENFT" },
  { id: "apeswap-finance", symbol: "banana", name: "ApeSwap" },
  { id: "ape-universe", symbol: "apeu", name: "Ape Universe" },
  { id: "apexit-finance", symbol: "apex", name: "ApeXit Finance" },
  { id: "apex-protocol", symbol: "apxp", name: "APEX Protocol" },
  { id: "apex-token-2", symbol: "apex", name: "ApeX" },
  { id: "api3", symbol: "api3", name: "API3" },
  { id: "apix", symbol: "apix", name: "APIX" },
  { id: "apm-coin", symbol: "apm", name: "apM Coin" },
  { id: "apollo", symbol: "apl", name: "Apollo" },
  { id: "apollo-crypto", symbol: "apollo", name: "Apollo Crypto" },
  { id: "apollon-limassol", symbol: "apl", name: "Apollon Limassol Fan Token" },
  { id: "apollo-token", symbol: "apollo", name: "Apollo Token" },
  { id: "apollox-2", symbol: "apx", name: "ApolloX" },
  { id: "appcoins", symbol: "appc", name: "AppCoins" },
  { id: "appics", symbol: "apx", name: "Appics" },
  { id: "apple-binemon", symbol: "amb", name: "Apple (Binemon)" },
  { id: "apple-tokenized-stock-defichain", symbol: "daapl", name: "Apple Tokenized Stock Defichain" },
  { id: "apricot", symbol: "aprt", name: "Apricot" },
  { id: "april", symbol: "april", name: "April" },
  { id: "apron", symbol: "apn", name: "Apron" },
  { id: "aptoge", symbol: "aptoge", name: "Aptoge" },
  { id: "aptos", symbol: "apt", name: "Aptos" },
  { id: "aptos-launch-token", symbol: "alt", name: "AptosLaunch Token" },
  { id: "apwine", symbol: "apw", name: "APWine" },
  { id: "apy-finance", symbol: "apy", name: "APY.Finance" },
  { id: "apyswap", symbol: "apys", name: "APYSwap" },
  { id: "apy-vision", symbol: "vision", name: "APY.vision" },
  { id: "aqtis", symbol: "aqtis", name: "AQTIS" },
  { id: "aquachain", symbol: "aqua", name: "Aquachain" },
  { id: "aquadao", symbol: "$aqua", name: "AquaDAO" },
  { id: "aqua-goat", symbol: "aquagoat", name: "Aqua Goat" },
  { id: "aquanee", symbol: "aqdc", name: "Aquanee" },
  { id: "aquari", symbol: "aquari", name: "Aquari" },
  { id: "aquarius", symbol: "aqua", name: "Aquarius" },
  { id: "aquariuscoin", symbol: "arco", name: "AquariusCoin" },
  { id: "aquarius-fi", symbol: "aqu", name: "Aquarius.Fi" },
  { id: "aquatank", symbol: "aqua", name: "AquaTank" },
  { id: "aqua-unicorn", symbol: "auni", name: "Aqua Unicorn" },
  { id: "arabian-doge", symbol: "$adoge", name: "Arabian Doge" },
  { id: "arabic", symbol: "abic", name: "Arabic" },
  { id: "arable-protocol", symbol: "acre", name: "Arable Protocol" },
  { id: "arable-usd", symbol: "arusd", name: "Arable USD" },
  { id: "aragon", symbol: "ant", name: "Aragon" },
  { id: "ara-token", symbol: "ara", name: "Ara" },
  { id: "arbdoge-ai", symbol: "aidoge", name: "ArbDoge AI" },
  { id: "arbidoge", symbol: "adoge", name: "ArbiDoge" },
  { id: "arbigoat", symbol: "agt", name: "ArbiGoat" },
  { id: "arbinu", symbol: "arbinu", name: "Arbinu" },
  { id: "arbinyan", symbol: "nyan", name: "ArbiNYAN" },
  { id: "arbiroul-casino-chip", symbol: "roul", name: "ArbiRoul Casino Chip" },
  { id: "arbis-finance", symbol: "arbis", name: "Arbis Finance" },
  { id: "arbismart-token", symbol: "rbis", name: "ArbiSmart" },
  { id: "arbisphere-launchpad", symbol: "arsh", name: "Arbisphere Launchpad" },
  { id: "arbiswap-42983059-37e1-4a8f-b46e-0d908c0d4cc0", symbol: "arbi", name: "ArbiSwap" },
  { id: "arbiten", symbol: "arbiten", name: "ArbiTen" },
  { id: "arbiten-10share", symbol: "10share", name: "ArbiTen 10SHARE" },
  { id: "arbitrum", symbol: "arb", name: "Arbitrum" },
  { id: "arbitrum-charts", symbol: "arcs", name: "Arbitrum Charts" },
  { id: "arbitrum-exchange", symbol: "arx", name: "Arbidex" },
  { id: "arbitrumpad", symbol: "arbpad", name: "ArbitrumPad" },
  { id: "arbi-wiz", symbol: "awiz", name: "Arbi Wiz" },
  { id: "arb-protocol", symbol: "arb", name: "ARB Protocol" },
  { id: "arbucks", symbol: "buck", name: "Arbucks" },
  { id: "arbys", symbol: "arbys", name: "Arbys" },
  { id: "arbzilla", symbol: "zilla", name: "ArbZilla" },
  { id: "arc", symbol: "arc", name: "Arc" },
  { id: "arcade2earn", symbol: "arcade", name: "Arcade2Earn" },
  { id: "arcade-canine", symbol: "okinu", name: "Arcade Canine" },
  { id: "arcade-kingdoms", symbol: "ack", name: "Arcade Kingdoms" },
  { id: "arcadeum", symbol: "arc", name: "Arcadeum" },
  { id: "arcadium", symbol: "arcadium", name: "Arcadium" },
  { id: "arcblock", symbol: "abt", name: "Arcblock" },
  { id: "arcc", symbol: "arcc", name: "ARCC" },
  { id: "archangel-token", symbol: "archa", name: "ArchAngel" },
  { id: "arch-blockchains", symbol: "chain", name: "Arch Blockchains" },
  { id: "archer-dao-governance-token", symbol: "arch", name: "Archer DAO Governance" },
  { id: "archerswap-bow", symbol: "bow", name: "Archerswap BOW" },
  { id: "archerswap-hunter", symbol: "hunt", name: "ArcherSwap Hunter" },
  { id: "arch-ethereum-web3", symbol: "web3", name: "Arch Ethereum Web3" },
  { id: "archethic", symbol: "uco", name: "Archethic" },
  { id: "archie-neko", symbol: "archie", name: "Archie Neko" },
  { id: "archimedes", symbol: "arch", name: "Archimedes Finance" },
  { id: "archive-ai", symbol: "arcai", name: "Archive AI" },
  { id: "archloot", symbol: "alt", name: "ArchLoot" },
  { id: "arcona", symbol: "arcona", name: "Arcona" },
  { id: "arcs", symbol: "arx", name: "ARCS" },
  { id: "ardana", symbol: "dana", name: "Ardana" },
  { id: "ardcoin", symbol: "ardx", name: "ArdCoin" },
  { id: "ardor", symbol: "ardr", name: "Ardor" },
  { id: "arenaplay", symbol: "apc", name: "ArenaPlay" },
  { id: "arena-token", symbol: "arena", name: "ArenaSwap" },
  { id: "arenum", symbol: "arnm", name: "Arenum" },
  { id: "areon-network", symbol: "area", name: "Areon Network" },
  { id: "ares3-network", symbol: "ares", name: "Ares3 Network" },
  { id: "ares-protocol", symbol: "ares", name: "Ares Protocol" },
  { id: "argentine-football-association-fan-token", symbol: "arg", name: "Argentine Football Association Fan Token" },
  { id: "argo", symbol: "argo", name: "ArGoApp" },
  { id: "argo-finance", symbol: "argo", name: "Argo Finance" },
  { id: "argon", symbol: "argon", name: "Argon" },
  { id: "argonon-helium", symbol: "arg", name: "Argonon Helium" },
  { id: "ari10", symbol: "ari10", name: "Ari10" },
  { id: "aria-currency", symbol: "ria", name: "aRIA Currency" },
  { id: "ariadne", symbol: "ardn", name: "Ariadne" },
  { id: "arianee", symbol: "aria20", name: "Arianee" },
  { id: "aries-financial-token", symbol: "afib", name: "Aries Financial" },
  { id: "arion", symbol: "arion", name: "Arion" },
  { id: "ari-swap", symbol: "ari", name: "Ari Swap" },
  { id: "ariva", symbol: "arv", name: "Ariva" },
  { id: "arix", symbol: "arix", name: "Arix" },
  { id: "arize", symbol: "arz", name: "ARize" },
  { id: "ark", symbol: "ark", name: "ARK" },
  { id: "arkadiko-protocol", symbol: "diko", name: "Arkadiko" },
  { id: "arkadiko-usda", symbol: "usda", name: "Arkadiko USDA" },
  { id: "arkania-protocol", symbol: "ania", name: "Arkania Protocol" },
  { id: "arken-finance", symbol: "$arken", name: "Arken Finance" },
  { id: "arker-2", symbol: "arker", name: "Arker" },
  { id: "ark-innovation-etf-defichain", symbol: "darkk", name: "ARK Innovation ETF Defichain" },
  { id: "ark-rivals", symbol: "arkn", name: "Ark Rivals" },
  { id: "armor", symbol: "armor", name: "ARMOR" },
  { id: "army-node-finance", symbol: "army", name: "Army Node Finance" },
  { id: "arnoya-classic", symbol: "arnc", name: "Arnoya classic" },
  { id: "arora", symbol: "aror", name: "Arora" },
  { id: "arowana-token", symbol: "arw", name: "Arowana" },
  { id: "arpa", symbol: "arpa", name: "ARPA" },
  { id: "arqma", symbol: "arq", name: "ArQmA" },
  { id: "arrow", symbol: "arw", name: "Arrow" },
  { id: "arsenal-fan-token", symbol: "afc", name: "Arsenal Fan Token" },
  { id: "artbyte", symbol: "aby", name: "ArtByte" },
  { id: "arte", symbol: "arte", name: "ARTE" },
  { id: "artem", symbol: "artem", name: "Artem" },
  { id: "artemis", symbol: "mis", name: "Artemis" },
  { id: "artemis-vision", symbol: "arv", name: "Artemis Vision" },
  { id: "arteq-nft-investment-fund", symbol: "arteq", name: "artèQ NFT Investment Fund" },
  { id: "artery", symbol: "artr", name: "Artery" },
  { id: "art-gobblers-goo", symbol: "goo", name: "Art Gobblers Goo" },
  { id: "artgpt", symbol: "agpt", name: "artGPT" },
  { id: "arth", symbol: "arth", name: "ARTH" },
  { id: "arthswap", symbol: "arsw", name: "ArthSwap" },
  { id: "artic-foundation", symbol: "artic", name: "ARTIC Foundation" },
  { id: "articoin", symbol: "atc", name: "ArtiCoin" },
  { id: "artificial-intelligence", symbol: "ai", name: "Artificial Intelligence" },
  {
    id: "artificial-intelligence-technology-network",
    symbol: "aitn",
    name: "Artificial Intelligence Technology Network",
  },
  { id: "artify", symbol: "afy", name: "Artify" },
  { id: "artik", symbol: "artk", name: "Artik" },
  { id: "arti-project", symbol: "arti", name: "Arti Project" },
  { id: "artizen", symbol: "atnt", name: "Artizen" },
  { id: "artkit", symbol: "arti", name: "ArtKit" },
  { id: "artl", symbol: "artl", name: "ARTL" },
  { id: "artm", symbol: "artm", name: "ARTM" },
  { id: "artmeta", symbol: "$mart", name: "ArtMeta" },
  { id: "artrade", symbol: "atr", name: "Artrade" },
  { id: "artube", symbol: "att", name: "Artube" },
  { id: "artx", symbol: "artx", name: "ARTX" },
  { id: "arweave", symbol: "ar", name: "Arweave" },
  { id: "aryacoin", symbol: "aya", name: "Aryacoin" },
  { id: "asan-verse", symbol: "asan", name: "ASAN VERSE" },
  { id: "ascension", symbol: "asn", name: "Ascension" },
  { id: "ascension-protocol", symbol: "ascend", name: "Ascension Protocol" },
  { id: "asd", symbol: "asd", name: "AscendEx" },
  { id: "asgard-games", symbol: "asg", name: "Asgard Games" },
  { id: "asgardian-aereus", symbol: "volt", name: "Asgardian Aereus" },
  { id: "asgardx", symbol: "odin", name: "AsgardX" },
  { id: "ash", symbol: "ash", name: "ASH" },
  { id: "ashera", symbol: "ash", name: "Ashera" },
  { id: "ashswap", symbol: "ash", name: "AshSwap" },
  { id: "ash-token", symbol: "ash", name: "Ash Token" },
  { id: "asia-coin", symbol: "asia", name: "Asia Coin" },
  { id: "asic-token", symbol: "asic", name: "ASIC Token" },
  { id: "asimi", symbol: "asimi", name: "ASIMI" },
  { id: "asix", symbol: "asix", name: "ASIX" },
  { id: "asixplus", symbol: "asix+", name: "AsixPlus" },
  { id: "ask-chip", symbol: "chip", name: "Ask Chip" },
  { id: "askobar-network", symbol: "asko", name: "Asko" },
  { id: "as-monaco-fan-token", symbol: "asm", name: "AS Monaco Fan Token" },
  { id: "aspire", symbol: "asp", name: "Aspire" },
  { id: "aspo-world", symbol: "aspo", name: "ASPO World" },
  { id: "as-roma-fan-token", symbol: "asr", name: "AS Roma Fan Token" },
  { id: "assangedao", symbol: "justice", name: "AssangeDAO" },
  { id: "assaplay", symbol: "assa", name: "AssaPlay" },
  { id: "assemble-protocol", symbol: "asm", name: "Assemble Protocol" },
  { id: "assent-protocol", symbol: "asnt", name: "Assent Protocol" },
  { id: "assetmantle", symbol: "mntl", name: "AssetMantle" },
  { id: "asta", symbol: "asta", name: "ASTA" },
  { id: "astar", symbol: "astr", name: "Astar" },
  { id: "aster", symbol: "atc", name: "Aster" },
  { id: "ast-finance", symbol: "ast", name: "AST.finance" },
  { id: "aston-martin-cognizant-fan-token", symbol: "am", name: "Aston Martin Cognizant Fan Token" },
  { id: "aston-villa-fan-token", symbol: "avl", name: "Aston Villa Fan Token" },
  { id: "astra-dao", symbol: "astra", name: "Astra DAO" },
  { id: "astrafer", symbol: "astrafer", name: "Astrafer" },
  { id: "astra-guild-ventures", symbol: "agv", name: "Astra Guild Ventures" },
  { id: "astral-ai", symbol: "astral", name: "Astral AI" },
  { id: "astral-credits", symbol: "xac", name: "Astral Credits" },
  { id: "astrals-glxy", symbol: "glxy", name: "Astrals GLXY" },
  { id: "astra-nova", symbol: "$rvv", name: "Astra Nova" },
  { id: "astra-protocol-2", symbol: "astra", name: "Astra Protocol" },
  { id: "astrazion", symbol: "aznt", name: "AstraZion" },
  { id: "astriddao-token", symbol: "atid", name: "AstridDAO" },
  { id: "astroai", symbol: "astroai", name: "AstroAI" },
  { id: "astro-babies", symbol: "abb", name: "Astro Babies" },
  { id: "astrobirdz", symbol: "abz", name: "AstroBirdz" },
  { id: "astro-cash", symbol: "astro", name: "Astro Cash" },
  { id: "astroelon", symbol: "elonone", name: "AstroElon" },
  { id: "astronaut", symbol: "naut", name: "Astronaut" },
  { id: "astroport", symbol: "astroc", name: "Astroport Classic" },
  { id: "astroport-fi", symbol: "astro", name: "Astroport" },
  { id: "astrospaces-io", symbol: "spaces", name: "AstroSpaces.io" },
  { id: "astroswap", symbol: "astro", name: "AstroSwap" },
  { id: "astrotools", symbol: "astro", name: "AstroTools" },
  { id: "astro-verse", symbol: "asv", name: "Astro Verse" },
  { id: "astrox", symbol: "atx", name: "AstroX" },
  { id: "asva", symbol: "asva", name: "Asva Labs" },
  { id: "asyagro", symbol: "asy", name: "ASYAGRO" },
  { id: "atari", symbol: "atri", name: "Atari" },
  { id: "athena-returns-olea", symbol: "olea", name: "Olea Token" },
  { id: "athenas", symbol: "athenasv2", name: "Athenas" },
  { id: "atheneum", symbol: "aem", name: "Atheneum" },
  { id: "athens", symbol: "ath", name: "Athens" },
  { id: "athos-finance", symbol: "ath", name: "Athos Finance" },
  { id: "athos-finance-usd", symbol: "athusd", name: "Athos Finance USD" },
  { id: "atlantis", symbol: "atlas", name: "Atlantis" },
  { id: "atlantis-coin", symbol: "atc", name: "Atlantis Coin" },
  { id: "atlantis-loans", symbol: "atl", name: "Atlantis Loans" },
  { id: "atlantis-loans-polygon", symbol: "atlx", name: "Atlantis Loans Polygon" },
  { id: "atlantis-metaverse", symbol: "tau", name: "Atlantis Metaverse" },
  { id: "atlas-aggregator", symbol: "ata", name: "Atlas Aggregator" },
  { id: "atlas-dex", symbol: "ats", name: "Atlas DEX" },
  { id: "atlas-fc-fan-token", symbol: "atlas", name: "Atlas FC Fan Token" },
  { id: "atlas-navi", symbol: "navi", name: "Atlas Navi" },
  { id: "atlas-protocol", symbol: "atp", name: "Atlas Protocol" },
  { id: "atlas-usv", symbol: "usv", name: "Atlas USV" },
  { id: "atletico-madrid", symbol: "atm", name: "Atletico Madrid Fan Token" },
  { id: "atomic-wallet-coin", symbol: "awc", name: "Atomic Wallet Coin" },
  { id: "atompad", symbol: "atpad", name: "AtomPad" },
  { id: "atpay", symbol: "atpay", name: "AtPay" },
  { id: "atrollcity", symbol: "pine", name: "Atrollcity" },
  { id: "atromg8", symbol: "ag8", name: "ATROMG8" },
  { id: "attack-wagon", symbol: "atk", name: "Attack Wagon" },
  { id: "attila", symbol: "att", name: "Attila" },
  { id: "auction", symbol: "auction", name: "Bounce" },
  { id: "auctus", symbol: "auc", name: "Auctus" },
  { id: "auditchain", symbol: "audt", name: "Auditchain" },
  { id: "audius", symbol: "audio", name: "Audius" },
  { id: "audius-wormhole", symbol: "audio", name: "Audius (Wormhole)" },
  { id: "augmented-finance", symbol: "agf", name: "Augmented Finance" },
  { id: "augur", symbol: "rep", name: "Augur" },
  { id: "augury-finance", symbol: "omen", name: "Augury Finance" },
  { id: "aura-bal", symbol: "aurabal", name: "Aura BAL" },
  { id: "auradx", symbol: "dalle2", name: "AuradX" },
  { id: "aura-finance", symbol: "aura", name: "Aura Finance" },
  { id: "auragi", symbol: "agi", name: "Auragi" },
  { id: "aura-network", symbol: "aura", name: "Aura Network" },
  { id: "aureo", symbol: "aur", name: "AUREO" },
  { id: "aureus-nummus-gold", symbol: "ang", name: "Aureus Nummus Gold" },
  { id: "auric-network", symbol: "auscm", name: "Auric Network" },
  { id: "aurigami", symbol: "ply", name: "Aurigami" },
  { id: "aurix", symbol: "aur", name: "Aurix" },
  { id: "aurora", symbol: "aoa", name: "Aurora Chain" },
  { id: "auroracoin", symbol: "aur", name: "Auroracoin" },
  { id: "aurora-dao", symbol: "idex", name: "IDEX" },
  { id: "aurora-near", symbol: "aurora", name: "Aurora" },
  { id: "auroratoken", symbol: "aurora", name: "AuroraToken" },
  { id: "aurora-token", symbol: "$adtx", name: "Aurora Dimension" },
  { id: "aurory", symbol: "aury", name: "Aurory" },
  { id: "aurusx", symbol: "ax", name: "AurusX" },
  { id: "ausdc", symbol: "ausdc", name: "SpaceShipX aUSDC" },
  { id: "australian-safe-shepherd", symbol: "ass", name: "Australian Safe Shepherd" },
  { id: "authencity", symbol: "auth", name: "Authencity" },
  { id: "auto", symbol: "auto", name: "Auto" },
  { id: "autobahn-network", symbol: "txl", name: "Autobahn Network" },
  { id: "auto-core", symbol: "acore", name: "Auto Core" },
  { id: "autocrypto", symbol: "au", name: "AutoCrypto" },
  { id: "automata", symbol: "ata", name: "Automata" },
  { id: "autominingtoken", symbol: "amt", name: "AutoMiningToken" },
  { id: "auton", symbol: "atn", name: "Auton" },
  { id: "autonio", symbol: "niox", name: "Autonio" },
  { id: "autoshark", symbol: "jaws", name: "AutoShark" },
  { id: "autosingle", symbol: "autos", name: "AutoSingle" },
  { id: "auto-staked-alex", symbol: "atalex", name: "Auto Staked ALEX" },
  { id: "autumn", symbol: "autumn", name: "Autumn" },
  { id: "aux-coin", symbol: "aux", name: "AUX Coin" },
  { id: "auxilium", symbol: "aux", name: "Auxilium" },
  { id: "avadex-token", symbol: "avex", name: "AvaDex Token" },
  { id: "avalanche-2", symbol: "avax", name: "Avalanche" },
  { id: "avalanche-wormhole", symbol: "avax", name: "Avalanche (Wormhole)" },
  { id: "avalaunch", symbol: "xava", name: "Avalaunch" },
  { id: "avaocado-dao", symbol: "avg", name: "Avocado DAO" },
  { id: "avata-network", symbol: "avat", name: "AVATA Network" },
  { id: "avatara-nox", symbol: "nox", name: "AVATARA NOX" },
  { id: "avatar-musk-verse", symbol: "amv", name: "Avatar Musk Verse" },
  { id: "avatly", symbol: "ava", name: "Avatly" },
  { id: "avaware", symbol: "ave", name: "Avaware" },
  { id: "avaxlauncher", symbol: "avxl", name: "Avaxlauncher" },
  { id: "avaxtars", symbol: "avxt", name: "Avaxtars" },
  { id: "avefarm", symbol: "ave", name: "AveFarm" },
  { id: "aventus", symbol: "avt", name: "Aventus" },
  { id: "avenue-hamilton-token", symbol: "aht", name: "Avenue Hamilton Token" },
  { id: "avenue-university-token", symbol: "aut", name: "Avenue University Token" },
  { id: "avian-network", symbol: "avn", name: "AVIAN" },
  { id: "avinoc", symbol: "avinoc", name: "AVINOC" },
  { id: "avme", symbol: "avme", name: "AVME" },
  { id: "avnrich", symbol: "avn", name: "AVNRich" },
  { id: "avocado", symbol: "avo", name: "Avocado" },
  { id: "avocadocoin", symbol: "avdo", name: "AvocadoCoin" },
  { id: "avoteo", symbol: "avo", name: "Avoteo" },
  { id: "axe", symbol: "axe", name: "Axe" },
  { id: "axel", symbol: "axel", name: "AXEL" },
  { id: "axelar", symbol: "axl", name: "Axelar" },
  { id: "axia", symbol: "axiav3", name: "Axia" },
  { id: "axial-token", symbol: "axial", name: "Axial Token" },
  { id: "axie-infinity", symbol: "axs", name: "Axie Infinity" },
  { id: "axie-infinity-shard-wormhole", symbol: "axset", name: "Axie Infinity Shard (Wormhole)" },
  { id: "axioms", symbol: "axi", name: "Axioms" },
  { id: "axion", symbol: "axn", name: "Axion" },
  { id: "axis-defi", symbol: "axis", name: "Axis DeFi" },
  { id: "axis-token", symbol: "axis", name: "AXIS" },
  { id: "axle-games", symbol: "axle", name: "Axle Games" },
  { id: "axl-inu", symbol: "axl", name: "AXL INU" },
  { id: "axlusdc", symbol: "axlusdc", name: "Axelar USDC" },
  { id: "axlwbtc", symbol: "axlwbtc", name: "axlWBTC" },
  { id: "axlweth", symbol: "axlweth", name: "axlWETH" },
  { id: "axpire", symbol: "axpr", name: "Moola" },
  { id: "azacoin", symbol: "aza", name: "AzaCoin" },
  { id: "azbit", symbol: "az", name: "Azbit" },
  { id: "azit", symbol: "azit", name: "azit" },
  { id: "aztec-nodes-sun", symbol: "sun", name: "Aztec Nodes SUN" },
  { id: "azuki", symbol: "azuki", name: "Azuki" },
  { id: "azuma-coin", symbol: "azum", name: "Azuma Coin" },
  { id: "az-world-socialfi", symbol: "azw", name: "AZ World SocialFi" },
  { id: "b20", symbol: "b20", name: "B20" },
  { id: "b8dex", symbol: "b8t", name: "B8DEX" },
  { id: "baanx", symbol: "bxx", name: "Baanx" },
  { id: "baasid", symbol: "baas", name: "BaaSid" },
  { id: "babacoin", symbol: "bbc", name: "Babacoin" },
  { id: "babb", symbol: "bax", name: "BABB" },
  { id: "babil-token", symbol: "babil", name: "BABIL TOKEN" },
  { id: "baby-alvey", symbol: "balvey", name: "Baby Alvey" },
  { id: "babyapefunclub", symbol: "bafc", name: "BabyApeFunClub" },
  { id: "baby-aptos", symbol: "baptos", name: "Baby Aptos" },
  { id: "baby-arbitrum", symbol: "barb", name: "Baby Arbitrum" },
  { id: "baby-bali", symbol: "bb", name: "Baby Bali" },
  { id: "baby-bitcoin", symbol: "bbtc", name: "Baby Bitcoin" },
  { id: "babybnb", symbol: "babybnb", name: "BabyBNB" },
  { id: "babybnbtiger", symbol: "babybnbtig", name: "BabyBNBTiger" },
  { id: "babyboo", symbol: "babyboo", name: "BabyBoo" },
  { id: "baby-boxer", symbol: "bboxer", name: "Baby Boxer" },
  { id: "babybusd", symbol: "babybusd", name: "BabyBUSD" },
  { id: "baby-cake", symbol: "babycake", name: "Baby Cake" },
  { id: "baby-catcoin", symbol: "babycats", name: "Baby Catcoin" },
  { id: "babydogecake", symbol: "bdc", name: "BabyDogeCake" },
  { id: "baby-doge-cash", symbol: "babydogecash", name: "Baby Doge Cash" },
  { id: "baby-doge-ceo", symbol: "babyceo", name: "Baby Doge CEO" },
  { id: "babydoge-ceo", symbol: "bceo", name: "BabyDoge CEO" },
  { id: "baby-doge-coin", symbol: "babydoge", name: "Baby Doge Coin" },
  { id: "babydoge-coin-eth", symbol: "babydoge", name: "BabyDoge ETH" },
  { id: "baby-doge-inu", symbol: "$babydogeinu", name: "Baby Doge Inu" },
  { id: "babydogezilla", symbol: "babydogezilla", name: "BabyDogeZilla" },
  { id: "babydot", symbol: "bdot", name: "BabyDot" },
  { id: "babyfloki", symbol: "babyfloki", name: "BabyFloki" },
  { id: "baby-floki", symbol: "babyfloki", name: "Baby Floki" },
  { id: "baby-floki-coin", symbol: "babyflokicoin", name: "Baby Floki Coin" },
  { id: "baby-floki-doge", symbol: "babyfd", name: "Baby Floki Doge" },
  { id: "baby-floki-inu", symbol: "bfloki", name: "Baby Floki Inu" },
  { id: "babyfootball", symbol: "cup", name: "BabyFootball" },
  { id: "baby-g", symbol: "babyg", name: "Baby G" },
  { id: "baby-kishu", symbol: "babykishu", name: "Baby Kishu" },
  { id: "babykitty", symbol: "babykitty", name: "BabyKitty" },
  { id: "baby-lambo-inu", symbol: "blinu", name: "Baby Lambo Inu" },
  { id: "babylon-finance", symbol: "babl", name: "Babylon Finance" },
  { id: "babylons", symbol: "babi", name: "Babylons" },
  { id: "baby-lovely-inu", symbol: "blovely", name: "Baby Lovely Inu" },
  { id: "baby-moon-floki", symbol: "floki", name: "Baby Moon Floki" },
  { id: "babyokx", symbol: "babyokx", name: "BABYOKX (BSC)" },
  { id: "babyokx-2", symbol: "babyokx", name: "BABYOKX" },
  { id: "babypepe", symbol: "babypepe", name: "BabyPepe" },
  { id: "baby-pig-token", symbol: "babypig", name: "Baby Pig" },
  { id: "baby-pokemoon", symbol: "bpm", name: "Baby Pokemoon" },
  { id: "babyrabbit", symbol: "babyrabbit", name: "Babyrabbit" },
  { id: "baby-ripple", symbol: "babyxrp", name: "Baby Ripple" },
  { id: "baby-saitama", symbol: "babysaitama", name: "Baby Saitama" },
  { id: "baby-samo-coin", symbol: "baby", name: "Baby Samo Coin" },
  { id: "baby-satoshi", symbol: "sats", name: "Baby Satoshi" },
  { id: "baby-shark", symbol: "shark", name: "Baby Shark" },
  { id: "baby-shark-tank", symbol: "bashtank", name: "Baby Shark Tank" },
  { id: "baby-shiba-coin", symbol: "babyshiba", name: "Baby Shiba Coin" },
  { id: "baby-shiba-inu", symbol: "babyshibainu", name: "Baby Shiba Inu" },
  { id: "babyshibby-inu", symbol: "babyshib", name: "BabyShibby Inu" },
  { id: "babyswap", symbol: "baby", name: "BabySwap" },
  { id: "baby-trump", symbol: "babytrump", name: "Baby Trump" },
  { id: "babywhale", symbol: "bbw", name: "BabyWhale" },
  { id: "baby-woj", symbol: "bwj", name: "Baby WOJ" },
  { id: "babyxrp", symbol: "bbyxrp", name: "BabyXrp" },
  { id: "backed-protocol", symbol: "bakt", name: "Backed Protocol" },
  { id: "bacondao", symbol: "bacon", name: "BaconDAO" },
  { id: "bacon-protocol-home", symbol: "home", name: "Home" },
  { id: "badger-dao", symbol: "badger", name: "Badger DAO" },
  { id: "badger-sett-badger", symbol: "bbadger", name: "Badger Sett Badger" },
  { id: "bafi-finance-token", symbol: "bafi", name: "Bafi Finance" },
  { id: "bahtcoin", symbol: "bht", name: "Bahtcoin" },
  { id: "bai-stablecoin", symbol: "bai", name: "BAI Stablecoin" },
  { id: "baitcoin", symbol: "bait", name: "Baitcoin" },
  { id: "baked-token", symbol: "baked", name: "Baked" },
  { id: "bakerytoken", symbol: "bake", name: "BakerySwap" },
  { id: "bakerytools", symbol: "tbake", name: "BakeryTools" },
  { id: "baklava", symbol: "bava", name: "Baklava" },
  { id: "balance-network", symbol: "bln", name: "Balance Network" },
  { id: "balancer", symbol: "bal", name: "Balancer" },
  { id: "balancer-80-bal-20-weth", symbol: "b-80bal-20weth", name: "Balancer 80 BAL 20 WETH" },
  { id: "balancer-boosted-aave-dai", symbol: "bb-a-dai", name: "Balancer Boosted Aave DAI" },
  { id: "balancer-boosted-aave-usdc", symbol: "bb-a-usdc", name: "Balancer Boosted Aave USDC" },
  { id: "balancer-boosted-aave-usdt", symbol: "bb-a-usdt", name: "Balancer Boosted Aave USDT" },
  { id: "balicoin", symbol: "bali", name: "Bali Coin" },
  { id: "balikesirspor-token", symbol: "blks", name: "Balıkesirspor Token" },
  { id: "bali-social-integrated", symbol: "bsi", name: "Bali Social Integrated" },
  { id: "bali-token", symbol: "bli", name: "Bali Token" },
  { id: "bali-united-fc-fan-token", symbol: "bufc", name: "Bali United FC Fan Token" },
  { id: "balkari-token", symbol: "bkr", name: "Balkari" },
  { id: "ball-coin", symbol: "ball", name: "BALL Coin" },
  { id: "balloonsville-air", symbol: "air", name: "Balloonsville AIR" },
  { id: "ballswap", symbol: "bsp", name: "BallSwap" },
  { id: "ball-token", symbol: "ball", name: "Ball" },
  { id: "balpha", symbol: "balpha", name: "bAlpha" },
  { id: "balto-token", symbol: "balto", name: "Balto Token" },
  { id: "bamboo-coin", symbol: "bmbo", name: "Bamboo Coin" },
  { id: "bamboo-defi", symbol: "bamboo", name: "BambooDeFi" },
  { id: "bamboo-token-c90b31ff-8355-41d6-a495-2b16418524c2", symbol: "bbo", name: "PandaFarm (BBO)" },
  { id: "banana", symbol: "banana", name: "Banana" },
  { id: "bananaclubtoken", symbol: "bct", name: "BananaClubToken" },
  { id: "banana-task-force-ape", symbol: "btfa", name: "Banana Task Force Ape" },
  { id: "bananatok", symbol: "bna", name: "BananaTok" },
  { id: "banana-token", symbol: "bnana", name: "Chimpion" },
  { id: "banano", symbol: "ban", name: "Banano" },
  { id: "banca", symbol: "banca", name: "Banca" },
  { id: "bancor", symbol: "bnt", name: "Bancor Network" },
  { id: "bancor-governance-token", symbol: "vbnt", name: "Bancor Governance" },
  { id: "band-protocol", symbol: "band", name: "Band Protocol" },
  { id: "bankera", symbol: "bnk", name: "Bankera" },
  { id: "bankers-dream", symbol: "bank$", name: "Bankers Dream" },
  { id: "bankless-bed-index", symbol: "bed", name: "Bankless BED Index" },
  { id: "bankless-dao", symbol: "bank", name: "Bankless DAO" },
  { id: "bankless-defi-innovation-index", symbol: "gmi", name: "Bankless DeFi Innovation Index" },
  { id: "bankroll-extended-token", symbol: "bnkrx", name: "Bankroll Extended" },
  { id: "bankroll-network", symbol: "bnkr", name: "Bankroll Network" },
  { id: "bankroll-vault", symbol: "vlt", name: "Bankroll Vault" },
  { id: "banksocial", symbol: "bsl", name: "BankSocial" },
  { id: "bantu", symbol: "xbn", name: "Bantu" },
  { id: "bao", symbol: "bao", name: "BAO" },
  { id: "bao-finance", symbol: "bao", name: "Bao Finance" },
  { id: "bao-finance-v2", symbol: "bao", name: "Bao Finance V2" },
  { id: "baousd", symbol: "baousd", name: "baoUSD" },
  { id: "baptlabs", symbol: "bapt", name: "BaptLabs" },
  { id: "barbecueswap", symbol: "bbq", name: "BarbecueSwap" },
  { id: "bard-protocol", symbol: "bard", name: "Bard Protocol" },
  { id: "bark", symbol: "bark", name: "Bark" },
  { id: "barking", symbol: "bark", name: "Barking" },
  { id: "barnbridge", symbol: "bond", name: "BarnBridge" },
  { id: "barter", symbol: "brtr", name: "Barter" },
  { id: "bartertrade", symbol: "bart", name: "BarterTrade" },
  { id: "basan", symbol: "basan", name: "Basan" },
  { id: "based-ai", symbol: "bai", name: "Based AI" },
  { id: "based-finance", symbol: "based", name: "Based Finance" },
  { id: "based-shares", symbol: "bshare", name: "BASED Shares" },
  { id: "base-protocol", symbol: "base", name: "Base Protocol" },
  { id: "basic", symbol: "basic", name: "BASIC" },
  { id: "basic-attention-token", symbol: "bat", name: "Basic Attention" },
  { id: "basilisk", symbol: "bsx", name: "Basilisk" },
  { id: "basis-cash", symbol: "bac", name: "Basis Cash" },
  { id: "basis-gold-share-heco", symbol: "bags", name: "Basis Gold Share (Heco)" },
  { id: "basis-markets", symbol: "basis", name: "basis.markets" },
  { id: "basis-share", symbol: "bas", name: "Basis Share" },
  { id: "basketball-legends", symbol: "bbl", name: "Basketball Legends" },
  { id: "basketcoin", symbol: "bskt", name: "BasketCoin" },
  { id: "baskonia-fan-token", symbol: "bkn", name: "Baskonia Fan Token" },
  { id: "bastion-protocol", symbol: "bstn", name: "Bastion Protocol" },
  { id: "bata", symbol: "bta", name: "Bata" },
  { id: "battle-esports-coin", symbol: "bes", name: "battle esports coin" },
  { id: "battlefly", symbol: "gfly", name: "BattleFly" },
  { id: "battle-for-giostone", symbol: "bfg", name: "Battle For Giostone" },
  { id: "battleforten", symbol: "bft", name: "BattleForTEN" },
  { id: "battle-hero", symbol: "bath", name: "Battle Hero" },
  { id: "battle-infinity", symbol: "ibat", name: "Battle Infinity" },
  { id: "battle-of-guardians-share", symbol: "bgs", name: "Battle of Guardians Share" },
  { id: "battle-pets", symbol: "pet", name: "Hello Pets" },
  { id: "battle-saga", symbol: "btl", name: "Battle Saga" },
  { id: "battleverse", symbol: "bvc", name: "BattleVerse" },
  { id: "battle-world", symbol: "bwo", name: "Battle World" },
  { id: "bayc-vault-nftx", symbol: "bayc", name: "BAYC Vault (NFTX)" },
  { id: "baymax-finance", symbol: "bay", name: "BayMax Finance" },
  { id: "bazaars", symbol: "bzr", name: "Bazaars" },
  { id: "bb-gaming", symbol: "bb", name: "BB Gaming" },
  { id: "bbs-network", symbol: "bbs", name: "BBS Network" },
  { id: "bcpay-fintech", symbol: "bcpay", name: "BCPAY FinTech" },
  { id: "b-cube-ai", symbol: "bcube", name: "B-cube.ai" },
  { id: "bdollar", symbol: "bdo", name: "bDollar" },
  { id: "beach-token", symbol: "beach", name: "Beach Token" },
  { id: "beacon", symbol: "becn", name: "Beacon" },
  { id: "beagle-inu", symbol: "bic", name: "Beagle Inu" },
  { id: "beam", symbol: "beam", name: "BEAM" },
  { id: "beamswap", symbol: "glint", name: "BeamSwap" },
  { id: "bean", symbol: "bean", name: "Bean" },
  { id: "bean-cash", symbol: "bitb", name: "Bean Cash" },
  { id: "bear-inu", symbol: "bear", name: "Bear Inu" },
  { id: "beatgen-nft", symbol: "bgn", name: "BeatGen NFT" },
  { id: "beatzcoin", symbol: "btzc", name: "BeatzCoin" },
  {
    id: "beauty-bakery-linked-operation-transaction-technology",
    symbol: "lott",
    name: "Beauty Bakery Linked Operation Transaction Technology",
  },
  { id: "becoswap-token", symbol: "beco", name: "BecoSwap" },
  { id: "bedrock", symbol: "rock", name: "Bedrock" },
  { id: "bee-capital", symbol: "bee", name: "Bee Capital" },
  { id: "beechat", symbol: "chat", name: "BeeChat" },
  { id: "beeco", symbol: "bgc", name: "Bee Token" },
  { id: "beefy-escrowed-fantom", symbol: "beftm", name: "Beefy Escrowed Fantom" },
  { id: "beefy-finance", symbol: "bifi", name: "Beefy.Finance" },
  { id: "beenode", symbol: "bnode", name: "Beenode" },
  { id: "beer-money", symbol: "beer", name: "Beer Money" },
  { id: "beeruscat", symbol: "bcat", name: "BeerusCat" },
  { id: "beethoven-x", symbol: "beets", name: "Beethoven X" },
  { id: "befasterholdertoken", symbol: "bfht", name: "BeFaster Holder Token" },
  { id: "befitter", symbol: "fiu", name: "beFITTER" },
  { id: "befitter-health", symbol: "hee", name: "beFITTER Health" },
  { id: "be-gaming-coin", symbol: "bgc", name: "Be Gaming Coin" },
  { id: "beholder", symbol: "eye", name: "Behodler" },
  { id: "bela", symbol: "aqua", name: "Bela Aqua" },
  { id: "beldex", symbol: "bdx", name: "Beldex" },
  { id: "belecx-protocol", symbol: "bex", name: "BelecX Protocol" },
  { id: "belifex", symbol: "befx", name: "Belifex" },
  { id: "bella-protocol", symbol: "bel", name: "Bella Protocol" },
  { id: "bellcoin", symbol: "bell", name: "Bellcoin" },
  { id: "belt", symbol: "belt", name: "Belt" },
  { id: "beluga-fi", symbol: "beluga", name: "Beluga.fi" },
  { id: "bemchain", symbol: "bcn", name: "Bemchain" },
  { id: "be-meta-famous", symbol: "bmf", name: "Be Meta Famous" },
  { id: "bemil-coin", symbol: "bem", name: "Bemil Coin" },
  { id: "benchmark-protocol", symbol: "mark", name: "Benchmark Protocol" },
  { id: "benddao", symbol: "bend", name: "BendDAO" },
  { id: "bened", symbol: "bnd", name: "Bened" },
  { id: "benqi", symbol: "qi", name: "BENQI" },
  { id: "benqi-liquid-staked-avax", symbol: "savax", name: "BENQI Liquid Staked AVAX" },
  { id: "bent-finance", symbol: "bent", name: "Bent Finance" },
  { id: "benzene", symbol: "bzn", name: "Benzene" },
  { id: "bep20-leo", symbol: "bleo", name: "BEP20 LEO" },
  { id: "bepay", symbol: "becoin", name: "bePAY Finance" },
  { id: "bepro-network", symbol: "bepro", name: "BEPRO Network" },
  { id: "bergerdoge", symbol: "bergerdoge", name: "BergerDoge" },
  { id: "bermuda", symbol: "bmda", name: "Bermuda" },
  { id: "berry", symbol: "berry", name: "Berry" },
  { id: "berry-data", symbol: "bry", name: "Berry Data" },
  { id: "berryswap", symbol: "berry", name: "BerrySwap" },
  { id: "berylbit", symbol: "brb", name: "Berylbit Layer-3 Network" },
  { id: "beshare-token", symbol: "bst", name: "Beshare" },
  { id: "beskar", symbol: "bsk-baa025", name: "Beskar" },
  { id: "bestay", symbol: "bsy", name: "Bestay" },
  { id: "bet2bank", symbol: "bxb", name: "Bet2Bank" },
  { id: "beta-finance", symbol: "beta", name: "Beta Finance" },
  { id: "beta-token", symbol: "beta", name: "Beta" },
  { id: "betaverse", symbol: "bet", name: "Betaverse" },
  { id: "betcoin", symbol: "bet", name: "BETCOIN" },
  { id: "betero", symbol: "bte", name: "Betero" },
  { id: "betgosu", symbol: "gosu", name: "BetGosu" },
  { id: "betswap-gg", symbol: "bsgg", name: "Betswap.gg" },
  { id: "betswirl", symbol: "bets", name: "BetSwirl" },
  { id: "betted", symbol: "bet", name: "Betted" },
  { id: "betterfan", symbol: "bff", name: "BetterFan" },
  { id: "betterment-digital", symbol: "bemd", name: "Betterment Digital" },
  { id: "better-money", symbol: "better", name: "Better Money" },
  { id: "betu", symbol: "betu", name: "Betu" },
  { id: "beyondcoin", symbol: "bynd", name: "Beyondcoin" },
  { id: "beyond-finance", symbol: "byn", name: "Beyondfi" },
  { id: "beyondpay", symbol: "bpay", name: "Beyondpay" },
  { id: "beyond-protocol", symbol: "bp", name: "Beyond Protocol" },
  { id: "bezoge-earth", symbol: "bezoge", name: "Bezoge Earth" },
  { id: "bfg-token", symbol: "bfg", name: "BetFury" },
  { id: "bficoin", symbol: "bfic", name: "Bficoin" },
  { id: "bfk-warzone", symbol: "bfk", name: "BFK WARZONE" },
  { id: "bgan-vault-nftx", symbol: "bgan", name: "BGAN Vault (NFTX)" },
  { id: "bhbd", symbol: "bhbd", name: "bHBD" },
  { id: "bhive", symbol: "bhive", name: "bHIVE" },
  { id: "bhnetwork", symbol: "bhat", name: "BHNetwork" },
  { id: "bho-network", symbol: "bho", name: "BHO Network" },
  { id: "biblecoin", symbol: "bibl", name: "Biblecoin" },
  { id: "biblepay", symbol: "bbp", name: "BiblePay" },
  { id: "bibox-token", symbol: "bix", name: "Bibox" },
  { id: "bib-token", symbol: "bib", name: "BIB Token" },
  { id: "biconomy", symbol: "bico", name: "Biconomy" },
  { id: "biconomy-exchange-token", symbol: "bit", name: "Biconomy Exchange" },
  { id: "bicyclefi", symbol: "bcf", name: "BicycleFi" },
  { id: "bidao", symbol: "bid", name: "Bidao" },
  { id: "bidao-smart-chain", symbol: "bisc", name: "Bidao Smart Chain" },
  { id: "bidipass", symbol: "bdp", name: "BidiPass" },
  { id: "bidz-coin", symbol: "bidz", name: "BIDZ Coin" },
  { id: "bifi", symbol: "bifi", name: "BiFi" },
  { id: "bifrost", symbol: "bfc", name: "Bifrost" },
  { id: "bifrost-native-coin", symbol: "bnc", name: "Bifrost Native Coin" },
  { id: "bigcap", symbol: "bigcap", name: "BIGCAP" },
  { id: "big-crypto-game", symbol: "crypto", name: "Big Crypto Game" },
  { id: "big-data-protocol", symbol: "bdp", name: "Big Data Protocol" },
  { id: "big-defi-energy", symbol: "bde", name: "Big Defi Energy" },
  { id: "big-digital-shares", symbol: "bds", name: "Big Digital Shares" },
  { id: "big-dog-coin", symbol: "bdog", name: "Big Dog Coin" },
  { id: "biggerminds", symbol: "mind+", name: "BiggerMINDS" },
  { id: "bigshortbets", symbol: "bigsb", name: "BigShortBets" },
  { id: "big-turn", symbol: "turn", name: "Big Turn" },
  { id: "bikerush", symbol: "brt", name: "Bikerush" },
  { id: "bilira", symbol: "tryb", name: "BiLira" },
  { id: "billiard-crypto", symbol: "bic", name: "Billiard Crypto" },
  { id: "billionaire-plus", symbol: "bplus", name: "Billionaire Plus" },
  { id: "billionaires-pixel-club", symbol: "bpc", name: "Billionaires Pixel Club" },
  { id: "billionhappiness", symbol: "bhc", name: "BillionHappiness" },
  { id: "binamon", symbol: "bmon", name: "Binamon" },
  { id: "binance-bitcoin", symbol: "btcb", name: "Binance Bitcoin" },
  { id: "binancecoin", symbol: "bnb", name: "BNB" },
  { id: "binance-coin-wormhole", symbol: "bnb", name: "Binance Coin (Wormhole)" },
  { id: "binance-eth", symbol: "beth", name: "Binance ETH staking" },
  { id: "binanceidr", symbol: "bidr", name: "BIDR" },
  { id: "binance-multi-chain-capital", symbol: "bmcc", name: "Binance Multi-Chain Capital" },
  { id: "binance-peg-avalanche", symbol: "avax", name: "Binance-Peg Avalanche" },
  { id: "binance-peg-bitcoin-cash", symbol: "bch", name: "Binance-Peg Bitcoin Cash" },
  { id: "binance-peg-cardano", symbol: "ada", name: "Binance-Peg Cardano" },
  { id: "binance-peg-dogecoin", symbol: "doge", name: "Binance-Peg Dogecoin" },
  { id: "binance-peg-eos", symbol: "eos", name: "Binance-Peg EOS" },
  { id: "binance-peg-filecoin", symbol: "fil", name: "Binance-Peg Filecoin" },
  { id: "binance-peg-firo", symbol: "firo", name: "Binance-Peg Firo" },
  { id: "binance-peg-iotex", symbol: "iotx", name: "Binance-Peg IoTeX" },
  { id: "binance-peg-litecoin", symbol: "ltc", name: "Binance-Peg Litecoin" },
  { id: "binance-peg-ontology", symbol: "ont", name: "Binance-Peg Ontology" },
  { id: "binance-peg-polkadot", symbol: "dot", name: "Binance-Peg Polkadot" },
  { id: "binance-peg-xrp", symbol: "xrp", name: "Binance-Peg XRP" },
  { id: "binance-smart-chain-girl", symbol: "bscgirl", name: "Binance Smart Chain Girl" },
  { id: "binance-usd", symbol: "busd", name: "Binance USD" },
  { id: "binance-wrapped-btc", symbol: "bbtc", name: "Binance Wrapped BTC" },
  { id: "binance-wrapped-dot", symbol: "bdot", name: "Binance Wrapped DOT" },
  { id: "binapet", symbol: "bpet", name: "Binapet" },
  { id: "binarydao", symbol: "byte", name: "BinaryDAO" },
  { id: "binaryx", symbol: "bnx", name: "BinaryX [OLD]" },
  { id: "binaryx-2", symbol: "bnx", name: "BinaryX" },
  { id: "bincentive", symbol: "bcnt", name: "Bincentive" },
  { id: "binemon", symbol: "bin", name: "Binemon" },
  { id: "bingo", symbol: "$bingo", name: "Tomorrowland" },
  { id: "binjit-coin", symbol: "bnj", name: "Binjit Coin" },
  { id: "binopoly", symbol: "bino", name: "Binopoly" },
  { id: "binspirit", symbol: "binspirit", name: "binSPIRIT" },
  { id: "binstarter", symbol: "bsr", name: "BinStarter" },
  { id: "bintex-futures", symbol: "bntx", name: "Bintex Futures" },
  { id: "biometric-financial", symbol: "biofi", name: "BiometricFinancial" },
  { id: "biopassport", symbol: "biot", name: "Bio Passport" },
  { id: "bios", symbol: "bios", name: "0x_nodes" },
  { id: "birake", symbol: "bir", name: "Birake" },
  { id: "birb-2", symbol: "birb", name: "Birb" },
  { id: "bird-money", symbol: "bird", name: "Bird.Money" },
  { id: "birdtoken", symbol: "birdtoken", name: "birdToken" },
  { id: "biskit-protocol", symbol: "biskit", name: "Biskit Protocol" },
  { id: "bismuth", symbol: "bis", name: "Bismuth" },
  { id: "bistroo", symbol: "bist", name: "Bistroo" },
  { id: "biswap", symbol: "bsw", name: "Biswap" },
  { id: "bit2me", symbol: "b2m", name: "Bit2Me" },
  { id: "bitant", symbol: "bitant", name: "BitANT" },
  { id: "bitazza", symbol: "btz", name: "Bitazza" },
  { id: "bitball", symbol: "btb", name: "Bitball" },
  { id: "bitbar", symbol: "btb", name: "Bitbar" },
  { id: "bitbase-token", symbol: "btbs", name: "BitBase Token" },
  { id: "bitbook-token", symbol: "bbt", name: "BitBook" },
  { id: "bitboost", symbol: "bbt", name: "BitBoost" },
  { id: "bitcanna", symbol: "bcna", name: "BitCanna" },
  { id: "bitcash", symbol: "bitc", name: "BitCash" },
  { id: "bitcastle", symbol: "castle", name: "bitcastle" },
  { id: "bitcci-cash", symbol: "bitcca", name: "Bitcci Cash" },
  { id: "bitcicoin", symbol: "bitci", name: "Bitcicoin" },
  { id: "bitci-racing-token", symbol: "brace", name: "Bitci Racing Token" },
  { id: "bitcoin", symbol: "btc", name: "Bitcoin" },
  { id: "bitcoin-2", symbol: "btc2", name: "Bitcoin 2" },
  { id: "bitcoin-and-ethereum-standard-token", symbol: "best", name: "Bitcoin and Ethereum Standard" },
  { id: "bitcoin-anonymous", symbol: "btca", name: "Bitcoin Anonymous" },
  { id: "bitcoin-asia", symbol: "btca", name: "Bitcoin Asia" },
  { id: "bitcoin-asset-2", symbol: "bta", name: "Bitcoin Asset" },
  { id: "bitcoin-atom", symbol: "bca", name: "Bitcoin Atom" },
  { id: "bitcoin-avalanche-bridged-btc-b", symbol: "btc.b", name: "Bitcoin Avalanche Bridged (BTC.b)" },
  { id: "bitcoinbam", symbol: "btcbam", name: "BitcoinBam" },
  { id: "bitcoin-bep2", symbol: "btcb", name: "Bitcoin BEP2" },
  { id: "bitcoin-br", symbol: "btcbr", name: "Bitcoin BR" },
  { id: "bitcoin-cash", symbol: "bch", name: "Bitcoin Cash" },
  { id: "bitcoin-cash-sv", symbol: "bsv", name: "Bitcoin SV" },
  { id: "bitcoin-city-coin", symbol: "bcity", name: "Bitcoin City Coin" },
  { id: "bitcoin-confidential", symbol: "bc", name: "Bitcoin Confidential" },
  { id: "bitcoin-diamond", symbol: "bcd", name: "Bitcoin Diamond" },
  { id: "bitcoin-e-wallet", symbol: "bitwallet", name: "Bitcoin E-wallet" },
  { id: "bitcoin-fast", symbol: "bcf", name: "Bitcoin Fast" },
  { id: "bitcoin-free-cash", symbol: "bfc", name: "Bitcoin Free Cash" },
  { id: "bitcoin-god", symbol: "god", name: "Bitcoin God" },
  { id: "bitcoin-gold", symbol: "btg", name: "Bitcoin Gold" },
  { id: "bitcoin-green", symbol: "bitg", name: "Bitcoin Green" },
  { id: "bitcoin-hd", symbol: "bhd", name: "Bitcoin HD" },
  { id: "bitcoin-international", symbol: "btci", name: "Bitcoin International" },
  { id: "bitcoin-latinum", symbol: "ltnm", name: "Bitcoin Latinum" },
  { id: "bitcoin-legend", symbol: "bcl", name: "Bitcoin Legend" },
  { id: "bitcoin-lightning", symbol: "bltg", name: "Block-Logic" },
  { id: "bitcoinmono", symbol: "btcmz", name: "BitcoinMono" },
  { id: "bitcoin-pay", symbol: "btcpay", name: "Bitcoin Pay" },
  { id: "bitcoin-plus", symbol: "xbc", name: "Bitcoin Plus" },
  { id: "bitcoinpos", symbol: "btcs", name: "BitcoinPoS" },
  { id: "bitcoin-private", symbol: "btcp", name: "Bitcoin Private" },
  { id: "bitcoin-pro", symbol: "btcp", name: "Bitcoin Pro" },
  { id: "bitcoin-red", symbol: "btcred", name: "Bitcoin Red" },
  { id: "bitcoin-scrypt", symbol: "btcs", name: "Bitcoin Scrypt" },
  { id: "bitcoin-subsidium", symbol: "xbtx", name: "Bitcoin Subsidium" },
  { id: "bitcoin-trc20", symbol: "btct", name: "Bitcoin TRC20" },
  { id: "bitcoin-trust", symbol: "bct", name: "Bitcoin Trust" },
  { id: "bitcointry-token", symbol: "btty", name: "Bitcointry Token" },
  { id: "bitcoinv", symbol: "btcv", name: "BitcoinV" },
  { id: "bitcoin-vault", symbol: "btcv", name: "Bitcoin Vault" },
  { id: "bitcoinvb", symbol: "btcvb", name: "BitcoinVB" },
  { id: "bitcoinx", symbol: "bcx", name: "BitcoinX" },
  { id: "bitcoinx-2", symbol: "btcx", name: "BitcoinXGames" },
  { id: "bitcoinz", symbol: "btcz", name: "BitcoinZ" },
  { id: "bitcoiva", symbol: "bca", name: "Bitcoiva" },
  { id: "bitcomine", symbol: "bme", name: "BitcoMine" },
  { id: "bitconey", symbol: "bitconey", name: "BitConey" },
  { id: "bitcore", symbol: "btx", name: "BitCore" },
  { id: "bitdao", symbol: "bit", name: "BitDAO" },
  { id: "bite", symbol: "bite", name: "BITE" },
  { id: "bitenium-token", symbol: "bt", name: "Bitenium" },
  { id: "bitflowers", symbol: "petal", name: "bitFlowers" },
  { id: "bitforex", symbol: "bf", name: "Bitforex" },
  { id: "bit-game-verse-token", symbol: "bgvt", name: "Bit Game Verse Token" },
  { id: "bitgear", symbol: "gear", name: "Bitgear" },
  { id: "bitgem", symbol: "xbtg", name: "Bitgem" },
  { id: "bitget-token", symbol: "bgb", name: "Bitget Token" },
  { id: "bitguild", symbol: "plat", name: "BitGuild PLAT" },
  { id: "bithachi", symbol: "bith", name: "Bithachi" },
  { id: "bithash-token", symbol: "bt", name: "BitHash" },
  { id: "bit-hotel", symbol: "bth", name: "Bit Hotel" },
  { id: "bitica-coin", symbol: "bdcc", name: "BITICA COIN" },
  { id: "bitindi-chain", symbol: "bni", name: "Bitindi Chain" },
  { id: "bitkub-coin", symbol: "kub", name: "Bitkub Coin" },
  { id: "bitlocus", symbol: "btl", name: "Bitlocus" },
  { id: "bitmark", symbol: "marks", name: "Bitmark" },
  { id: "bitmart-token", symbol: "bmx", name: "BitMart" },
  { id: "bitmex-token", symbol: "bmex", name: "BitMEX" },
  { id: "bitmon", symbol: "bit", name: "Bitmon" },
  { id: "bitnautic", symbol: "btntv2", name: "BitNautic" },
  { id: "bito-coin", symbol: "bito", name: "BITO Coin" },
  { id: "bitone", symbol: "bio", name: "BITONE" },
  { id: "bitorbit", symbol: "bitorb", name: "BitOrbit" },
  { id: "bitoreum", symbol: "btrm", name: "Bitoreum" },
  { id: "bitpaid-token", symbol: "btp", name: "Bitpaid" },
  { id: "bitpanda-ecosystem-token", symbol: "best", name: "Bitpanda Ecosystem" },
  { id: "bitrise-token", symbol: "brise", name: "Bitgert" },
  { id: "bitrue-token", symbol: "btr", name: "Bitrue Coin" },
  { id: "bitscrow", symbol: "btscrw", name: "Bitscrow" },
  { id: "bitshares", symbol: "bts", name: "BitShares" },
  { id: "bitshiba", symbol: "shiba", name: "BitShiba" },
  { id: "bitsong", symbol: "btsg", name: "BitSong" },
  { id: "bitspawn", symbol: "spwn", name: "Bitspawn" },
  { id: "bitstake", symbol: "xbs", name: "BitStake" },
  { id: "bitsten-token", symbol: "bst", name: "Bitsten [OLD]" },
  { id: "bit-store-coin", symbol: "store", name: "Bit Store" },
  { id: "bitstubs", symbol: "stub", name: "BitStubs" },
  { id: "bitsum", symbol: "mat", name: "Matka" },
  { id: "bittensor", symbol: "tao", name: "Bittensor" },
  { id: "bittoken", symbol: "bitt", name: "BITT" },
  { id: "bittorrent", symbol: "btt", name: "BitTorrent" },
  { id: "bittorrent-old", symbol: "bttold", name: "BitTorrent [OLD]" },
  { id: "bittube", symbol: "tube", name: "BitTube" },
  { id: "bittwatt", symbol: "bwt", name: "Bittwatt" },
  { id: "bitvalley", symbol: "bitv", name: "BitValley" },
  { id: "bitvote", symbol: "btv", name: "Bitvote" },
  { id: "bitwhite", symbol: "btw", name: "BitWhite" },
  { id: "bitwin24", symbol: "bwi", name: "Bitwin24" },
  { id: "bitzen", symbol: "bzen", name: "Bitzen" },
  { id: "bitzipp", symbol: "bzp", name: "BitZipp" },
  { id: "biu-coin", symbol: "biu", name: "BIU COIN" },
  { id: "bixb-coin", symbol: "bixb", name: "BixB Coin" },
  { id: "bizzcoin", symbol: "bizz", name: "BIZZCOIN" },
  { id: "bkex-token", symbol: "bkk", name: "BKEX Chain" },
  { id: "blackcoin", symbol: "blk", name: "BlackCoin" },
  { id: "black-dragon-society", symbol: "bds", name: "Black Dragon Society" },
  { id: "blackdragon-token", symbol: "bdt", name: "BlackDragon" },
  { id: "black-eyed-dragon", symbol: "bleyd", name: "Black Eyed Dragon" },
  { id: "blackhat-coin", symbol: "blkc", name: "BlackHat Coin" },
  { id: "blackhole-protocol", symbol: "black", name: "BlackHole Protocol" },
  { id: "blackpearl-chain", symbol: "bplc", name: "BlackPearl" },
  { id: "black-phoenix", symbol: "bpx", name: "Black Phoenix" },
  { id: "blackpool-token", symbol: "bpt", name: "BlackPool" },
  { id: "black-rabbit-ai", symbol: "brain", name: "Black Rabbit AI" },
  { id: "black-stallion", symbol: "bs", name: "Black Stallion" },
  { id: "black-token", symbol: "black", name: "Black Token" },
  { id: "blade", symbol: "blade", name: "BladeWarrior" },
  { id: "blank", symbol: "blank", name: "BlockWallet" },
  { id: "blaze-network", symbol: "blzn", name: "Blaze Network" },
  { id: "blazestake-staked-sol", symbol: "bsol", name: "BlazeStake Staked SOL" },
  { id: "bless-global-credit", symbol: "blec", name: "Bless Global Credit" },
  { id: "blind-boxes", symbol: "bles", name: "Blind Boxes" },
  { id: "blin-metaverse", symbol: "blin", name: "Blin Metaverse" },
  { id: "blithe", symbol: "blt", name: "Blithe" },
  { id: "blitz-labs", symbol: "blitz", name: "Blitz Labs" },
  { id: "blitzpredict", symbol: "xbp", name: "BlitzPick" },
  { id: "blizzard", symbol: "xblzd", name: "Blizzard" },
  { id: "blizzard-network", symbol: "blizz", name: "Blizzard Network" },
  { id: "blizz-finance", symbol: "blzz", name: "Blizz Finance" },
  { id: "blocery", symbol: "bly", name: "Blocery" },
  { id: "block-ape-scissors", symbol: "bas", name: "Block Ape Scissors" },
  { id: "blockasset", symbol: "block", name: "Blockasset" },
  { id: "blockaura", symbol: "tbac", name: "BlockAura" },
  { id: "blockbank", symbol: "bbank", name: "blockbank" },
  { id: "blockbase", symbol: "bbt", name: "BlockBase" },
  { id: "blockblend", symbol: "bbl", name: "BlockBlend" },
  { id: "blockcdn", symbol: "bcdn", name: "BlockCDN" },
  { id: "blockchain-bets", symbol: "bcb", name: "Blockchain Bets" },
  { id: "blockchain-brawlers", symbol: "brwl", name: "Blockchain Brawlers" },
  { id: "blockchain-certified-data-token", symbol: "bcdt", name: "EvidenZ" },
  { id: "blockchain-cuties-universe-governance", symbol: "bcug", name: "Blockchain Cuties Universe Governance" },
  { id: "blockchain-euro-project", symbol: "bepr", name: "Blockchain Euro Project" },
  { id: "blockchaingames", symbol: "bcg", name: "BlockChainGames" },
  { id: "blockchain-monster-hunt", symbol: "bcmc", name: "Blockchain Monster Hunt" },
  { id: "blockchainpoland", symbol: "bcp", name: "BlockchainPoland" },
  { id: "blockchainspace", symbol: "guild", name: "BlockchainSpace" },
  { id: "block-commerce-protocol", symbol: "bcp", name: "Block Commerce Protocol" },
  { id: "block-creatures", symbol: "moolah", name: "Block Creatures" },
  { id: "block-e", symbol: "block-e", name: "BLOCK-E" },
  { id: "block-forest", symbol: "bft", name: "Block Forest" },
  { id: "blockless", symbol: "bls", name: "Blockless" },
  { id: "blockmason-credit-protocol", symbol: "bcpt", name: "Blockmason Credit Protocol" },
  { id: "blockmason-link", symbol: "blink", name: "BlockMason Link" },
  { id: "blockmax", symbol: "ocb", name: "BLOCKMAX" },
  { id: "block-monsters", symbol: "mnstrs", name: "Block Monsters" },
  { id: "blocknet", symbol: "block", name: "Blocknet" },
  { id: "blockombat", symbol: "bkb", name: "BlocKombat" },
  { id: "blockpad", symbol: "blos", name: "Blockius" },
  { id: "blockpass", symbol: "pass", name: "Blockpass" },
  { id: "blockport", symbol: "bux", name: "BUX" },
  { id: "blockportal", symbol: "bptl", name: "BlockPortal" },
  { id: "blockrock", symbol: "bro$", name: "BlockRock" },
  { id: "blocks", symbol: "blocks", name: "BLOCKS" },
  { id: "blocksafu", symbol: "bsafu", name: "BlockSafu" },
  { id: "blocksmith-labs-forge", symbol: "$forge", name: "Blocksmith Labs Forge" },
  { id: "blockspace-token", symbol: "bls", name: "Blocks Space" },
  { id: "blocksport", symbol: "bspt", name: "Blocksport" },
  { id: "blocksquare", symbol: "bst", name: "Blocksquare" },
  { id: "blockstack", symbol: "stx", name: "Stacks" },
  { id: "blockstar", symbol: "bst", name: "BlockStar" },
  { id: "blockster", symbol: "bxr", name: "Blockster" },
  { id: "blocksworkz", symbol: "blkz", name: "BlocksWorkz" },
  { id: "blockton", symbol: "bton", name: "Blockton" },
  { id: "blockv", symbol: "vee", name: "BLOCKv" },
  { id: "blockx", symbol: "bcx", name: "BlockX" },
  { id: "blockxpress", symbol: "bx", name: "BlockXpress" },
  { id: "bloc-money", symbol: "bloc", name: "Bloc.Money" },
  { id: "blocsport-one", symbol: "bls", name: "Metacourt" },
  { id: "blocto-token", symbol: "blt", name: "Blocto" },
  { id: "blokpad", symbol: "bpad", name: "BlokPad" },
  { id: "bloktopia", symbol: "blok", name: "Bloktopia" },
  { id: "bloody-bunny", symbol: "bony", name: "Bloody Bunny" },
  { id: "bloom", symbol: "blt", name: "Bloom" },
  { id: "blossom", symbol: "sakura", name: "Blossom" },
  { id: "blox", symbol: "cdt", name: "Blox" },
  { id: "bloxmove-erc20", symbol: "blxm", name: "bloXmove" },
  { id: "blox-token", symbol: "blox", name: "Blox SDK" },
  { id: "bluca", symbol: "bluc", name: "Bluca" },
  { id: "blueart", symbol: "bla", name: "BLUEART TOKEN" },
  { id: "blue-baikal", symbol: "bbc", name: "Blue Baikal" },
  { id: "bluebenx-2", symbol: "benx", name: "BlueBenx" },
  { id: "bluebit", symbol: "bbt", name: "BlueBit" },
  { id: "bluejay", symbol: "blu", name: "Bluejay" },
  { id: "bluelight", symbol: "kale", name: "Bluelight" },
  { id: "bluemove", symbol: "move", name: "BlueMove" },
  { id: "blueshift", symbol: "blues", name: "Blueshift" },
  { id: "bluesparrow", symbol: "bluesparrow", name: "BlueSparrow" },
  { id: "bluesparrow-token", symbol: "bluesparrow", name: "BlueSparrow [OLD]" },
  { id: "bluewizard", symbol: "wiz", name: "BlueWizard" },
  { id: "blur", symbol: "blur", name: "Blur" },
  { id: "blurt", symbol: "blurt", name: "Blurt" },
  { id: "bluzelle", symbol: "blz", name: "Bluzelle" },
  { id: "bmax", symbol: "bmax", name: "BMAX" },
  { id: "bmchain-token", symbol: "bmt", name: "BMCHAIN" },
  { id: "bnb48-club-token", symbol: "koge", name: "KOGE" },
  { id: "bnbback", symbol: "bnbback", name: "BNBBack" },
  { id: "bnb-bank", symbol: "bbk", name: "BNB Bank" },
  { id: "bnb-diamond", symbol: "bnbd", name: "BNB Diamond" },
  { id: "bnb-dragon", symbol: "bnbdragon", name: "BnB Dragon" },
  { id: "bnbpot", symbol: "bnbp", name: "BNBPot" },
  { id: "bnbtiger", symbol: "bnbtiger", name: "BNB Tiger Inu" },
  { id: "bnext-b3x", symbol: "b3x", name: "Bnext B3X" },
  { id: "bnktothefuture", symbol: "bft", name: "BnkToTheFuture" },
  { id: "bnpl-pay", symbol: "bnpl", name: "BNPL Pay" },
  { id: "bnsd-finance", symbol: "bnsd", name: "BNSD Finance" },
  { id: "bns-token", symbol: "bns", name: "BNS" },
  { id: "bns-token-old", symbol: "bns", name: "BNS Token [OLD]" },
  { id: "board", symbol: "board", name: "Board" },
  { id: "bob", symbol: "bob", name: "BOB" },
  { id: "boba-brewery", symbol: "bre", name: "Boba Brewery" },
  { id: "bobadoge", symbol: "bdoge", name: "BobaDoge" },
  { id: "boba-network", symbol: "boba", name: "Boba Network" },
  { id: "bobcoin", symbol: "bobc", name: "Bobcoin" },
  { id: "bobo", symbol: "bobo", name: "Bobo" },
  { id: "bobs_repair", symbol: "bob", name: "Bob's Repair" },
  { id: "bocachica", symbol: "chica", name: "BocaChica" },
  { id: "bocoin", symbol: "boc", name: "BOCOIN" },
  { id: "boda-token", symbol: "bodav2", name: "BODA" },
  { id: "bodrumspor-fan-token", symbol: "bdrm", name: "Bodrumspor Fan Token" },
  { id: "body-ai", symbol: "bait", name: "Body Ai" },
  { id: "bogged-finance", symbol: "bog", name: "Bogged Finance" },
  { id: "bohr-2", symbol: "br", name: "BoHr" },
  { id: "boid", symbol: "boid", name: "Boid" },
  { id: "boji", symbol: "boji", name: "BOJI" },
  { id: "boku", symbol: "boku", name: "Boryoku Dragonz" },
  { id: "bold-point", symbol: "bpt", name: "Bold Point" },
  { id: "bole-token", symbol: "bole", name: "Boleld" },
  { id: "bolide", symbol: "blid", name: "Bolide" },
  { id: "bolivarcoin", symbol: "boli", name: "Bolivarcoin" },
  { id: "bollycoin", symbol: "bolly", name: "BollyCoin" },
  { id: "bologna-fc-fan-token", symbol: "bfc", name: "Bologna FC Fan Token" },
  { id: "bolt", symbol: "bolt", name: "Bolt" },
  { id: "bomb", symbol: "bomb", name: "BOMB" },
  { id: "bombcrypto-coin", symbol: "bomb", name: "Bombcrypto Coin" },
  { id: "bomber-coin", symbol: "bcoin", name: "BombCrypto" },
  { id: "bomb-money", symbol: "bomb", name: "Bomb Money" },
  { id: "bomb-money-bshare", symbol: "bshare", name: "Bomb Money BShare" },
  { id: "bonded-cronos", symbol: "bcro", name: "Bonded Cronos" },
  { id: "bondly", symbol: "bondly", name: "Forj" },
  { id: "bondly-defi", symbol: "bond", name: "Bondly" },
  { id: "bone-2", symbol: "bone", name: "Bone" },
  { id: "bonerium-boneswap", symbol: "bswp", name: "Bonerium BoneSwap" },
  { id: "bone-shibaswap", symbol: "bone", name: "Bone ShibaSwap" },
  { id: "boneswap", symbol: "bone", name: "BoneSwap" },
  { id: "bone-token", symbol: "bone", name: "PolyPup Bone" },
  { id: "bonfi", symbol: "bnf", name: "BonFi" },
  { id: "bonfida", symbol: "fida", name: "Bonfida" },
  { id: "bonfire", symbol: "bonfire", name: "Bonfire" },
  { id: "bongweedcoin", symbol: "bwc", name: "BongWeedCoin" },
  { id: "bonk", symbol: "bonk", name: "Bonk" },
  { id: "bonq", symbol: "bnq", name: "Bonq" },
  { id: "bonq-euro", symbol: "beur", name: "Bonq Euro" },
  { id: "bontecoin", symbol: "bonte", name: "Bontecoin" },
  { id: "boo", symbol: "boo", name: "Boo" },
  { id: "boo-finance", symbol: "boofi", name: "Boo Finance" },
  { id: "boo-mirrorworld", symbol: "xboo", name: "Boo MirrorWorld" },
  { id: "boop", symbol: "boop", name: "Boop" },
  { id: "boosted-lusd", symbol: "blusd", name: "Boosted LUSD" },
  { id: "booster", symbol: "boo", name: "Booster" },
  { id: "bora", symbol: "bora", name: "BORA" },
  { id: "borderless-money", symbol: "bom", name: "Borderless Money" },
  { id: "borealis", symbol: "brl", name: "Borealis" },
  { id: "bored", symbol: "$bored", name: "Bored" },
  { id: "bored-apemove", symbol: "bape", name: "Bored APEmove" },
  { id: "bored-ape-social-club", symbol: "bape", name: "Bored Ape Social Club" },
  { id: "bored-candy-city", symbol: "candy", name: "Bored Candy City" },
  { id: "boredmemes", symbol: "boredm", name: "BoredMemes" },
  { id: "boringdao", symbol: "boring", name: "BoringDAO" },
  { id: "boringdao-[old]", symbol: "bor", name: "BoringDAO [OLD]" },
  { id: "boring-protocol", symbol: "bop", name: "Boring Protocol" },
  { id: "bosagora", symbol: "boa", name: "BOSagora" },
  { id: "boson-protocol", symbol: "boson", name: "Boson Protocol" },
  { id: "boss", symbol: "boss", name: "Boss" },
  { id: "bossdao", symbol: "boss", name: "BossDao" },
  { id: "bossswap", symbol: "boss", name: "Boss Swap" },
  { id: "bostrom", symbol: "boot", name: "Bostrom" },
  { id: "botopiafinance", symbol: "btop", name: "BotopiaFinance" },
  { id: "bot-planet", symbol: "bot", name: "Bot Planet" },
  { id: "botto", symbol: "botto", name: "Botto" },
  { id: "bottos", symbol: "bto", name: "Bottos" },
  { id: "botxcoin", symbol: "botx", name: "BOTXCOIN" },
  { id: "boulpik-token", symbol: "boulpik", name: "Boulpik Token" },
  { id: "bountie-hunter", symbol: "bountie", name: "Bountie Hunter" },
  { id: "bounty0x", symbol: "bnty", name: "Bounty0x" },
  { id: "bountymarketcap", symbol: "bmc", name: "BountyMarketCap" },
  { id: "bovineverse-bvt", symbol: "bvt", name: "Bovineverse BVT" },
  { id: "bowl-shibarium", symbol: "bowl", name: "BOWL SHIBARIUM" },
  { id: "bowscoin", symbol: "bsc", name: "BowsCoin" },
  { id: "boxa", symbol: "boxa", name: "BOXA" },
  { id: "boxaxis", symbol: "baxs", name: "BoxAxis" },
  { id: "boxcasino", symbol: "boxc", name: "BOXCASINO" },
  { id: "boxch", symbol: "boxch", name: "Utility Token Boxch" },
  { id: "boxerdoge", symbol: "boxerdoge", name: "BoxerDOGE" },
  { id: "boxer-inu", symbol: "boxer", name: "Boxer Inu" },
  { id: "bpegd", symbol: "bpeg", name: "BPEGd" },
  { id: "bpm", symbol: "bpm", name: "BPM" },
  { id: "b-protocol", symbol: "bpro", name: "B.Protocol" },
  { id: "bracelet", symbol: "brc", name: "Bracelet" },
  { id: "brain-sync", symbol: "syncbrain", name: "Brain Sync" },
  { id: "braintrust", symbol: "btrst", name: "Braintrust" },
  { id: "brandpad-finance", symbol: "brand", name: "BrandPad Finance" },
  { id: "brave-power-crystal", symbol: "bpc", name: "Brave Power Crystal" },
  { id: "brazil-fan-token", symbol: "bft", name: "Brazil National Football Team Fan Token" },
  { id: "brcp-token", symbol: "brcp", name: "BRCP" },
  { id: "bread", symbol: "brd", name: "Bread" },
  { id: "breederdao", symbol: "breed", name: "BreederDAO" },
  { id: "brewlabs", symbol: "brewlabs", name: "Brewlabs" },
  { id: "brick", symbol: "brick", name: "r/FortNiteBR Bricks" },
  { id: "brick-token", symbol: "brick", name: "Brick" },
  { id: "bridge-mutual", symbol: "bmi", name: "Bridge Mutual" },
];
